import CoherenceCalculus.Foundation.DyadicContinuumCore

/-!
# Foundation.DyadicIntervalCore

Explicit dyadic intervals and interval threads.

This module turns the binary refinement scaffold into genuine interval data on
the unit dyadic line. Each stage carries an interval of width `1 / 2^n`,
represented by adjacent endpoint indices over the mesh `powTwo n`.
-/

namespace CoherenceCalculus

/-- Dyadic interval at depth `n`, represented by adjacent endpoint indices over
the denominator `powTwo n`. -/
structure DyadicInterval (n : Nat) where
  leftIndex : Nat
  rightIndex : Nat
  unit_width : rightIndex = leftIndex + 1
  right_bound : rightIndex ≤ powTwo n

namespace DyadicInterval

/-- Extensionality for dyadic intervals. -/
theorem ext {n : Nat} {I J : DyadicInterval n}
    (hleft : I.leftIndex = J.leftIndex)
    (hright : I.rightIndex = J.rightIndex) : I = J := by
  cases I with
  | mk ileft iright iwidth ibound =>
      cases J with
      | mk jleft jright jwidth jbound =>
          cases hleft
          cases hright
          have hwidth : iwidth = jwidth := Subsingleton.elim _ _
          have hbound : ibound = jbound := Subsingleton.elim _ _
          cases hwidth
          cases hbound
          rfl

end DyadicInterval

/-- Root dyadic interval `[0,1]` on the unit mesh. -/
def rootInterval : DyadicInterval 0 where
  leftIndex := 0
  rightIndex := 1
  unit_width := rfl
  right_bound := Nat.le_refl 1

/-- Positivity of the dyadic mesh denominator. -/
theorem powTwo_pos (n : Nat) : 0 < powTwo n := by
  induction n with
  | zero =>
      decide
  | succ n ih =>
      rw [powTwo_step]
      exact Nat.mul_pos (by decide) ih

/-- The dyadic mesh strictly refines at the next stage. -/
theorem powTwo_lt_step (n : Nat) : powTwo n < powTwo (n + 1) := by
  rw [powTwo_step]
  have hpos : 0 < powTwo n := powTwo_pos n
  calc
    powTwo n < powTwo n + powTwo n := Nat.lt_add_of_pos_right hpos
    _ = 2 * powTwo n := by
          rw [Nat.two_mul]

/-- Left child of a dyadic interval. -/
def leftChildInterval {n : Nat} (I : DyadicInterval n) : DyadicInterval (n + 1) where
  leftIndex := 2 * I.leftIndex
  rightIndex := 2 * I.leftIndex + 1
  unit_width := rfl
  right_bound := by
    calc
      2 * I.leftIndex + 1 ≤ 2 * I.leftIndex + 2 := Nat.le_succ _
      _ = 2 * (I.leftIndex + 1) := by
            rw [Nat.mul_add]
      _ = 2 * I.rightIndex := by
            rw [I.unit_width]
      _ ≤ 2 * powTwo n := Nat.mul_le_mul_left 2 I.right_bound
      _ = powTwo (n + 1) := by
            rw [powTwo_step]

/-- Right child of a dyadic interval. -/
def rightChildInterval {n : Nat} (I : DyadicInterval n) : DyadicInterval (n + 1) where
  leftIndex := 2 * I.leftIndex + 1
  rightIndex := 2 * I.rightIndex
  unit_width := by
    calc
      2 * I.rightIndex = 2 * (I.leftIndex + 1) := by
            rw [I.unit_width]
      _ = 2 * I.leftIndex + (1 + 1) := by
            rw [Nat.mul_add]
      _ = (2 * I.leftIndex + 1) + 1 := by
            rw [Nat.add_assoc]
  right_bound := by
    calc
      2 * I.rightIndex ≤ 2 * powTwo n := Nat.mul_le_mul_left 2 I.right_bound
      _ = powTwo (n + 1) := by
            rw [powTwo_step]

/-- Every dyadic interval splits into two distinct children. -/
theorem child_intervals_distinct {n : Nat} (I : DyadicInterval n) :
    leftChildInterval I ≠ rightChildInterval I := by
  intro h
  have hleft :
      (leftChildInterval I).leftIndex = (rightChildInterval I).leftIndex := by
    exact congrArg DyadicInterval.leftIndex h
  dsimp [leftChildInterval, rightChildInterval] at hleft
  have : 2 * I.leftIndex = 2 * I.leftIndex + 1 := hleft
  exact Nat.succ_ne_self (2 * I.leftIndex) this.symm

/-- Dyadic interval determined by a dyadic cell. -/
def intervalOfCell : {n : Nat} → DyadicCell n → DyadicInterval n
  | 0, PartialChoice.nil => rootInterval
  | _ + 1, PartialChoice.snoc c BinaryDigit.left =>
      leftChildInterval (intervalOfCell c)
  | _ + 1, PartialChoice.snoc c BinaryDigit.right =>
      rightChildInterval (intervalOfCell c)

/-- Interval thread generated by an infinite binary sequence. -/
def intervalsOfDigits (digits : Nat → BinaryDigit) : (n : Nat) → DyadicInterval n
  | 0 => rootInterval
  | n + 1 =>
      match digits n with
      | BinaryDigit.left => leftChildInterval (intervalsOfDigits digits n)
      | BinaryDigit.right => rightChildInterval (intervalsOfDigits digits n)

/-- Left endpoint step formula for a digit-induced dyadic interval. -/
theorem intervalsOfDigits_leftIndex_step (digits : Nat → BinaryDigit) (n : Nat) :
    (intervalsOfDigits digits (n + 1)).leftIndex =
      match digits n with
      | BinaryDigit.left => 2 * (intervalsOfDigits digits n).leftIndex
      | BinaryDigit.right => 2 * (intervalsOfDigits digits n).leftIndex + 1 := by
  cases h : digits n with
  | left =>
      simp [intervalsOfDigits, h]
      rfl
  | right =>
      simp [intervalsOfDigits, h]
      rfl

/-- Right endpoint step formula for a digit-induced dyadic interval. -/
theorem intervalsOfDigits_rightIndex_step (digits : Nat → BinaryDigit) (n : Nat) :
    (intervalsOfDigits digits (n + 1)).rightIndex =
      match digits n with
      | BinaryDigit.left => 2 * (intervalsOfDigits digits n).leftIndex + 1
      | BinaryDigit.right => 2 * (intervalsOfDigits digits n).rightIndex := by
  cases h : digits n with
  | left =>
      simp [intervalsOfDigits, h]
      rfl
  | right =>
      simp [intervalsOfDigits, h]
      rfl

/-- Dyadic interval thread on the unit line. -/
structure DyadicIntervalThread where
  intervals : (n : Nat) → DyadicInterval n
  root : intervals 0 = rootInterval
  refine : ∀ n,
    intervals (n + 1) = leftChildInterval (intervals n) ∨
      intervals (n + 1) = rightChildInterval (intervals n)

/-- Every binary sequence induces a dyadic interval thread. -/
def intervalThreadOfDigits (digits : Nat → BinaryDigit) : DyadicIntervalThread where
  intervals := intervalsOfDigits digits
  root := rfl
  refine := by
    intro n
    cases hd : digits n with
    | left =>
        rw [intervalsOfDigits, hd]
        exact Or.inl rfl
    | right =>
        rw [intervalsOfDigits, hd]
        exact Or.inr rfl

/-- The stage-`n` interval in any digit thread has mesh denominator
`powTwo n`. -/
theorem intervalsOfDigits_mesh (digits : Nat → BinaryDigit) (n : Nat) :
    (intervalsOfDigits digits n).rightIndex ≤ powTwo n := by
  exact (intervalsOfDigits digits n).right_bound

end CoherenceCalculus
