import CoherenceCalculus.Foundation.DefectRuleCore
import CoherenceCalculus.Foundation.ProjectionCalculusCore
import CoherenceCalculus.Foundation.TargetCore

/-!
# Foundation.ObservableClosureCore

Early observable-relative closure grammar on the rebuilt additive state space.

This file covers the manuscript's operator-side observable packaging layer
without importing normed-space, quotient, or spectral machinery. The active
surface here is intentionally finite and explicit:

- typed coherence and bilinear defects on explicit projection cuts
- observable packages and paired observable packages
- direct observable transfer and Schur-return transfer
- task-perfect / source-visible / one-step-visible bookkeeping
- the task-visible defect package and its faithfulness classes
-/

namespace CoherenceCalculus

/-- Typed coherence defect on an explicit domain/codomain projection cut of the
rebuilt state space. -/
def typedCoherenceDefect
    (PX PY : Projection) (F : AddMap) (x : State) : State :=
  State.sub (PY (F x)) (F (PX x))

/-- Typed chain rule on the active additive state space. -/
theorem typed_chain_rule
    (PX PY PZ : Projection) (F G : AddMap) (x : State) :
    typedCoherenceDefect PX PZ (AddMap.comp F G) x =
      State.add
        (typedCoherenceDefect PY PZ F (G x))
        (State.sub (F (PY (G x))) (F (G (PX x)))) := by
  unfold typedCoherenceDefect
  exact
    (sub_eq_add_sub
      (PZ (F (G x)))
      (F (PY (G x)))
      (F (G (PX x)))).symm

/-- Typed bilinear defect on explicit source/test/output projection cuts. -/
def typedBilinearDefect
    (PY PX PZ : Projection) (B : State → State → State) (y x : State) : State :=
  State.sub (PZ (B y x)) (B (PY y) (PX x))

/-- Exact bilinear defect decomposition under visible-visible closure. -/
theorem typed_bilinear_defect_decomposition
    (PY PX PZ : Projection) (B : State → State → State)
    (hlinY : ∀ y₁ y₂ x, B (State.add y₁ y₂) x = State.add (B y₁ x) (B y₂ x))
    (hlinX : ∀ y x₁ x₂, B y (State.add x₁ x₂) = State.add (B y x₁) (B y x₂))
    (hclosure : ∀ y x, PZ (B (PY y) (PX x)) = B (PY y) (PX x))
    (y x : State) :
    typedBilinearDefect PY PX PZ B y x =
      State.add
        (PZ (B (PY y) (projectionShadow PX x)))
        (State.add
          (PZ (B (projectionShadow PY y) (PX x)))
          (PZ (B (projectionShadow PY y) (projectionShadow PX x)))) := by
  let py := PY y
  let qy := projectionShadow PY y
  let px := PX x
  let qx := projectionShadow PX x

  have hy : y = State.add py qy := by
    exact (shadow_plus_proj_identity PY y).symm
  have hx : x = State.add px qx := by
    exact (shadow_plus_proj_identity PX x).symm

  have h_expand :
      B y x =
        State.add
          (B py px)
          (State.add (B py qx) (State.add (B qy px) (B qy qx))) := by
    calc
      B y x = B (State.add py qy) x := by rw [hy]
      _ = State.add (B py x) (B qy x) := by rw [hlinY]
      _ = State.add (B py (State.add px qx)) (B qy x) := by rw [hx]
      _ = State.add (State.add (B py px) (B py qx)) (B qy x) := by rw [hlinX]
      _ = State.add (State.add (B py px) (B py qx)) (B qy (State.add px qx)) := by
            rw [hx]
      _ = State.add (State.add (B py px) (B py qx)) (State.add (B qy px) (B qy qx)) := by
            rw [hlinX]
      _ = State.add (B py px) (State.add (B py qx) (State.add (B qy px) (B qy qx))) := by
            rw [State.add_assoc]

  have h_proj :
      PZ (B y x) =
        State.add
          (PZ (B py px))
          (State.add
            (PZ (B py qx))
            (State.add (PZ (B qy px)) (PZ (B qy qx)))) := by
    rw [h_expand, PZ.map_add, PZ.map_add, PZ.map_add]

  unfold typedBilinearDefect
  rw [h_proj, hclosure]
  exact State.sub_eq_right_of_add_left rfl

/-- Observable package on the rebuilt state space. -/
structure ObservablePackage where
  source : State → Prop
  observable : AddMap

/-- Paired observable package on the rebuilt state space. The induced observable
is kept explicit on the active import-free lane. -/
structure PairedObservablePackage where
  source : State → Prop
  test : State → Prop
  pairingObservable : AddMap

/-- Direct observable transfer generated by the shadow part of the chosen cut. -/
def directObservableTransfer
    (Ω : ObservablePackage) (P : Projection) (A : AddMap) (x : State) : State :=
  Ω.observable (A (projectionShadow P x))

/-- Exact direct observable decomposition. -/
theorem direct_observable_decomposition
    (Ω : ObservablePackage) (P : Projection) (A : AddMap) (x : State) :
    Ω.observable (A x) =
      State.add (Ω.observable (A (P x))) (directObservableTransfer Ω P A x) := by
  unfold directObservableTransfer
  calc
    Ω.observable (A x)
        = Ω.observable (A (State.add (P x) (projectionShadow P x))) := by
            rw [shadow_plus_proj_identity]
    _ = Ω.observable (State.add (A (P x)) (A (projectionShadow P x))) := by
          rw [A.map_add]
    _ = State.add (Ω.observable (A (P x))) (Ω.observable (A (projectionShadow P x))) := by
          rw [Ω.observable.map_add]

/-- Observable Schur return transfer on the visible side of the chosen cut. -/
def observableSchurReturnTransfer
    (Ω : ObservablePackage) (P : Projection) (A Rqq : AddMap) (x : State) : State :=
  Ω.observable (schurComplement P A Rqq x)

/-- Fixed-source observable Schur return transfer on the active import-free
lane. -/
def fixedSourceObservableSchurReturnTransfer
    (Ω : ObservablePackage) (P : Projection) (A Rqq : AddMap) (x : State) : State :=
  Ω.observable (schurComplement P A Rqq (P x))

/-- The returned residual seen by the observable package is exactly the Schur
return transfer, and the effective observable law splits into the visible block
plus that returned residual. -/
theorem observable_return_is_schur
    (Ω : ObservablePackage) (P : Projection) (A Rqq : AddMap) (x : State) :
    Ω.observable (returnedResidual (residualReturnFieldOf P A Rqq) x) =
      observableSchurReturnTransfer Ω P A Rqq x ∧
      Ω.observable (effectiveOp P A Rqq x) =
        State.add (Ω.observable (blockPP P A x))
          (observableSchurReturnTransfer Ω P A Rqq x) := by
  constructor
  · unfold observableSchurReturnTransfer
    rw [returnedResidual_eq_schur]
  · unfold observableSchurReturnTransfer effectiveOp AddMap.add
    rw [Ω.observable.map_add]

/-- The fixed-source return transfer factors pointwise through the selected
projection. -/
theorem fixed_source_return_factorization
    (Ω : ObservablePackage) (P : Projection) (A Rqq : AddMap) (x : State) :
    fixedSourceObservableSchurReturnTransfer Ω P A Rqq x =
      observableSchurReturnTransfer Ω P A Rqq (P x) := by
  rfl

/-- On projection-fixed states, the fixed-source return transfer agrees with
the visible-side return transfer. -/
theorem fixed_source_return_on_fixed_points
    (Ω : ObservablePackage) (P : Projection) (A Rqq : AddMap) (x : State)
    (hx : P x = x) :
    fixedSourceObservableSchurReturnTransfer Ω P A Rqq x =
      observableSchurReturnTransfer Ω P A Rqq x := by
  unfold fixedSourceObservableSchurReturnTransfer observableSchurReturnTransfer
  rw [hx]

/-- Task-perfect coherence for an observable package. -/
def taskPerfectCoherence
    (Ω : ObservablePackage) (P : Projection) (A : AddMap) : Prop :=
  ∀ Rqq : AddMap, ∀ x : State, Ω.source x →
    fixedSourceObservableSchurReturnTransfer Ω P A Rqq x = State.zero

/-- Whole-state perfect coherence implies task-perfect coherence for every
observable package. -/
theorem perfect_implies_taskPerfect
    (Ω : ObservablePackage) (P : Projection) (A : AddMap)
    (hperfect : hasPerfectCoherence P A) :
    taskPerfectCoherence Ω P A := by
  intro Rqq x _hx
  unfold fixedSourceObservableSchurReturnTransfer
  rw [hperfect Rqq (P x), Ω.observable.map_zero]

/-- Source-visible loss of a projection cut relative to an observable package. -/
def sourceVisibleLoss
    (Ω : ObservablePackage) (P : Projection) (x : State) : State :=
  Ω.observable (projectionShadow P x)

/-- Task-visible defect package on the active additive state space. -/
structure TaskVisibleDefectPackage where
  sourceVisibleLoss : State → State
  directTransfer : State → State
  fixedSourceReturn : State → State

/-- Canonical task-visible defect package built from an observable package, a
projection cut, and an additive law with one explicit shadow propagator. -/
def taskVisibleDefectPackage
    (Ω : ObservablePackage) (P : Projection) (A Rqq : AddMap) :
    TaskVisibleDefectPackage where
  sourceVisibleLoss := sourceVisibleLoss Ω P
  directTransfer := directObservableTransfer Ω P A
  fixedSourceReturn := fixedSourceObservableSchurReturnTransfer Ω P A Rqq

/-- Task-visible faithfulness classes on the active import-free lane. -/
structure TaskVisibleFaithfulness
    (Ω : ObservablePackage) (P : Projection) (A : AddMap) where
  sourceFaithful : Prop
  oneStepFaithful : Prop
  taskExact : Prop
  sourceFaithful_def :
    sourceFaithful ↔ ∀ x : State, Ω.source x → sourceVisibleLoss Ω P x = State.zero
  oneStepFaithful_def :
    oneStepFaithful ↔ ∀ x : State, Ω.source x → directObservableTransfer Ω P A x = State.zero
  taskExact_def :
    taskExact ↔ sourceFaithful ∧ oneStepFaithful ∧ taskPerfectCoherence Ω P A

end CoherenceCalculus
