import CoherenceCalculus.PartIV.ClosureCurrentStateAssemblyCore

namespace CoherenceCalculus

/-!
# PartIV.ClosureCurrentTrajectoryCore

Discrete trajectory surface for the detached closure-current lane.

`ClosureCurrentStateAssemblyCore` reduces the hidden current to an explicit
three-coordinate balanced carrier and proves its one-step transport law. This
file adds the finite-step version needed for an honest simulation-facing
reading:

* repeated local exactification of the hidden pair current;
* repeated reduced transport on the three-coordinate hidden carrier;
* exact agreement between those two discrete trajectories.

This still sits on the detached Part IV lane. It does not yet force a concrete
numeric representative for the current carrier or the matched generator.
-/

namespace ClosureCurrent

private def iterateEndomorphism {α : Type} (F : α → α) : Nat → α → α
  | 0 => fun x => x
  | n + 1 => fun x => iterateEndomorphism F n (F x)

/-- Smallest pure four-state dynamics package carried by the detached lane:
one endomap of the explicit state carrier. -/
structure StateDynamics where
  step : State → State

namespace StateDynamics

/-- State trajectory generated by iterating the four-state update map from one
initial state. -/
def trajectoryFrom
    (data : StateDynamics)
    (x : State) :
    Nat → State :=
  fun n => iterateEndomorphism data.step n x

/-- The pure four-state trajectory satisfies its defining recurrence. -/
theorem trajectoryFrom_step
    (data : StateDynamics) :
    ∀ n : Nat,
      ∀ x : State,
        data.trajectoryFrom x (n + 1) =
          data.step (data.trajectoryFrom x n)
  | 0, x => rfl
  | n + 1, x => by
      simpa [trajectoryFrom, iterateEndomorphism] using
        data.trajectoryFrom_step n (data.step x)

/-- Starting the pure four-state trajectory one step later is the same as
applying the update map after `n` steps. -/
theorem trajectoryFrom_step_start
    (data : StateDynamics) :
    ∀ n : Nat,
      ∀ x : State,
        data.trajectoryFrom (data.step x) n =
          data.step (data.trajectoryFrom x n)
  | 0, x => rfl
  | n + 1, x => by
      simpa [trajectoryFrom, iterateEndomorphism] using
        data.trajectoryFrom_step_start n (data.step x)

end StateDynamics

/-- Pure initial-value package for the four-state detached dynamics. -/
structure StateDynamicsState where
  dynamics : StateDynamics
  initial : State

namespace StateDynamicsState

/-- Four-state trajectory generated from the chosen explicit initial state. -/
def trajectory
    (data : StateDynamicsState) :
    Nat → State :=
  data.dynamics.trajectoryFrom data.initial

/-- The four-state trajectory starts at the chosen explicit initial state. -/
theorem trajectory_zero
    (data : StateDynamicsState) :
    data.trajectory 0 = data.initial := by
  rfl

/-- The four-state trajectory satisfies the pure recurrence law. -/
theorem trajectory_step
    (data : StateDynamicsState) :
    ∀ n : Nat,
      data.trajectory (n + 1) =
        data.dynamics.step (data.trajectory n) := by
  intro n
  exact data.dynamics.trajectoryFrom_step n data.initial

end StateDynamicsState

/-- Iterated local exactification of the detached hidden pair current. -/
def AnchoredCurrentObject.exactifyIterate
    {Index Time Carrier Law : Type}
    (data : AnchoredCurrentObject Index Time Carrier Law) :
    Nat →
      PairExchangeCurrent data.currentCarrier data.Leg →
        PairExchangeCurrent data.currentCarrier data.Leg :=
  iterateEndomorphism data.exactifier.exactify

/-- One-step reduced hidden-current transport on the three-coordinate balanced
carrier. -/
def AnchoredCurrentObject.coordinateStep
    {Index Time Carrier Law : Type}
    (data : AnchoredCurrentObject Index Time Carrier Law) :
    BalancedCoordinates → BalancedCoordinates :=
  BalancedCoordinates.transport data.bridge.generator.toFun

/-- Selected observed readout of one reduced balanced hidden coordinate. -/
def BalancedCoordinates.observedReadout
    {Index Time Carrier Law : Type}
    (data : AnchoredCurrentObject Index Time Carrier Law) :
    BalancedCoordinates → State :=
  fun x => selectedProjection data.bridge x.toState

/-- Minimal simulation-facing detached system: one reduced hidden update map
and one selected observed readout from the same hidden carrier. -/
structure ReducedObservedSystem
    {Index Time Carrier Law : Type}
    (data : AnchoredCurrentObject Index Time Carrier Law) where
  hiddenStep : BalancedCoordinates → BalancedCoordinates
  observedReadout : BalancedCoordinates → State

/-- Smallest pure discrete dynamics package carried by the detached lane: one
reduced hidden update map and one observed readout, with no remaining
reference to a current object or selected bridge datum in the type itself. -/
structure ReducedObservedDynamics where
  hiddenStep : BalancedCoordinates → BalancedCoordinates
  observedReadout : BalancedCoordinates → State

namespace ReducedObservedDynamics

/-- Hidden orbit of the pure reduced observed dynamics from one initial reduced
hidden coordinate. -/
def hiddenTrajectoryFrom
    (data : ReducedObservedDynamics)
    (x : BalancedCoordinates) :
    Nat → BalancedCoordinates :=
  fun n => iterateEndomorphism data.hiddenStep n x

/-- Observed orbit of the pure reduced observed dynamics from one initial
reduced hidden coordinate. -/
def observedTrajectoryFrom
    (data : ReducedObservedDynamics)
    (x : BalancedCoordinates) :
    Nat → State :=
  fun n => data.observedReadout (data.hiddenTrajectoryFrom x n)

/-- The pure hidden orbit satisfies the defining recurrence. -/
theorem hiddenTrajectoryFrom_step
    (data : ReducedObservedDynamics) :
    ∀ n : Nat,
      ∀ x : BalancedCoordinates,
        data.hiddenTrajectoryFrom x (n + 1) =
          data.hiddenStep (data.hiddenTrajectoryFrom x n)
  | 0, x => rfl
  | n + 1, x => by
      simpa [hiddenTrajectoryFrom, iterateEndomorphism] using
        data.hiddenTrajectoryFrom_step n (data.hiddenStep x)

/-- The pure observed orbit is read from the pure hidden orbit by the observed
readout. -/
theorem observedTrajectoryFrom_readout
    (data : ReducedObservedDynamics)
    (x : BalancedCoordinates) :
    ∀ n : Nat,
      data.observedTrajectoryFrom x n =
        data.observedReadout (data.hiddenTrajectoryFrom x n) := by
  intro n
  rfl

end ReducedObservedDynamics

/-- Pure initial-value package for the reduced observed dynamics. -/
structure ReducedObservedDynamicsState where
  dynamics : ReducedObservedDynamics
  initial : BalancedCoordinates

namespace ReducedObservedDynamicsState

/-- Hidden orbit of the pure reduced observed dynamics from the chosen initial
reduced hidden coordinate. -/
def hiddenTrajectory
    (data : ReducedObservedDynamicsState) :
    Nat → BalancedCoordinates :=
  data.dynamics.hiddenTrajectoryFrom data.initial

/-- Observed orbit of the pure reduced observed dynamics from the chosen
initial reduced hidden coordinate. -/
def observedTrajectory
    (data : ReducedObservedDynamicsState) :
    Nat → State :=
  data.dynamics.observedTrajectoryFrom data.initial

/-- The hidden orbit starts at the chosen initial reduced hidden coordinate. -/
theorem hiddenTrajectory_zero
    (data : ReducedObservedDynamicsState) :
    data.hiddenTrajectory 0 = data.initial := by
  simp [ReducedObservedDynamicsState.hiddenTrajectory,
    ReducedObservedDynamics.hiddenTrajectoryFrom, iterateEndomorphism]

/-- The hidden orbit satisfies the pure reduced recurrence. -/
theorem hiddenTrajectory_step
    (data : ReducedObservedDynamicsState) :
    ∀ n : Nat,
      data.hiddenTrajectory (n + 1) =
        data.dynamics.hiddenStep (data.hiddenTrajectory n) := by
  intro n
  exact data.dynamics.hiddenTrajectoryFrom_step n data.initial

/-- The observed orbit is always read from the hidden orbit by the observed
readout. -/
theorem observedTrajectory_readout
    (data : ReducedObservedDynamicsState) :
    ∀ n : Nat,
      data.observedTrajectory n =
        data.dynamics.observedReadout (data.hiddenTrajectory n) := by
  intro n
  exact data.dynamics.observedTrajectoryFrom_readout data.initial n

end ReducedObservedDynamicsState

/-- Smallest bridge-driven reduced initial-state package: one selected bridge
generator, one selected projection, and one initial reduced hidden coordinate.
The hidden step and observed readout are no longer arbitrary data; they are
canonically induced from the selected bridge state map itself. -/
structure SelectedReducedState where
  generator : State → State
  projection : State → State
  initial : BalancedCoordinates

namespace SelectedReducedState

/-- Canonical reduced hidden step induced by the selected bridge generator. -/
def hiddenStep
    (data : SelectedReducedState) :
    BalancedCoordinates → BalancedCoordinates :=
  BalancedCoordinates.transport data.generator

/-- Hidden orbit induced by the selected bridge generator from the chosen
initial reduced hidden coordinate. -/
def hiddenTrajectory
    (data : SelectedReducedState) :
    Nat → BalancedCoordinates :=
  fun n => iterateEndomorphism data.hiddenStep n data.initial

/-- Observed orbit induced by the selected projection on the hidden orbit. -/
def observedTrajectory
    (data : SelectedReducedState) :
    Nat → State :=
  fun n => data.projection ((data.hiddenTrajectory n).toState)

/-- The bridge-driven hidden orbit starts at the chosen reduced initial
coordinate. -/
theorem hiddenTrajectory_zero
    (data : SelectedReducedState) :
    data.hiddenTrajectory 0 = data.initial := by
  simp [SelectedReducedState.hiddenTrajectory, iterateEndomorphism]

/-- The bridge-driven hidden orbit satisfies the selected-generator
recurrence. -/
private theorem hiddenTrajectoryFrom_step
    (data : SelectedReducedState) :
    ∀ n : Nat,
      ∀ x : BalancedCoordinates,
        iterateEndomorphism data.hiddenStep (n + 1) x =
          data.hiddenStep (iterateEndomorphism data.hiddenStep n x)
  | 0, x => rfl
  | n + 1, x => by
      simpa [iterateEndomorphism] using
        hiddenTrajectoryFrom_step data n (data.hiddenStep x)

/-- The bridge-driven hidden orbit satisfies the selected-generator
recurrence. -/
theorem hiddenTrajectory_step
    (data : SelectedReducedState) :
    ∀ n : Nat,
      data.hiddenTrajectory (n + 1) =
        data.hiddenStep (data.hiddenTrajectory n)
  := by
    intro n
    simpa [SelectedReducedState.hiddenTrajectory] using
      hiddenTrajectoryFrom_step data n data.initial

/-- The bridge-driven observed orbit is always the selected projection of the
current hidden reduced state. -/
theorem observedTrajectory_readout
    (data : SelectedReducedState) :
    ∀ n : Nat,
      data.observedTrajectory n =
        data.projection ((data.hiddenTrajectory n).toState) := by
  intro n
  rfl

/-- The bridge-driven reduced initial state determines the corresponding pure
reduced-dynamics initial state. -/
def toDynamicsState
    (data : SelectedReducedState) :
    ReducedObservedDynamicsState where
  dynamics := {
    hiddenStep := data.hiddenStep
    observedReadout := fun x => data.projection x.toState
  }
  initial := data.initial

/-- Passing to the pure reduced-dynamics package does not change the hidden
orbit. -/
theorem hiddenTrajectory_toDynamicsState
    (data : SelectedReducedState) :
    ∀ n : Nat,
      data.hiddenTrajectory n =
        data.toDynamicsState.hiddenTrajectory n := by
  intro n
  rfl

/-- Passing to the pure reduced-dynamics package does not change the observed
orbit. -/
theorem observedTrajectory_toDynamicsState
    (data : SelectedReducedState) :
    ∀ n : Nat,
      data.observedTrajectory n =
        data.toDynamicsState.observedTrajectory n := by
  intro n
  rfl

end SelectedReducedState

/-- Iterated hidden evolution in the reduced observed system. -/
def ReducedObservedSystem.hiddenIterate
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (system : ReducedObservedSystem data) :
    Nat → BalancedCoordinates → BalancedCoordinates :=
  iterateEndomorphism system.hiddenStep

/-- Iterated observed evolution in the reduced observed system. -/
def ReducedObservedSystem.observedIterate
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (system : ReducedObservedSystem data) :
    Nat → BalancedCoordinates → State :=
  fun n x => system.observedReadout (system.hiddenIterate n x)

/-- Equal initial reduced hidden coordinates determine the same hidden
trajectory in the reduced observed system. -/
theorem ReducedObservedSystem.hiddenIterate_congr
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (system : ReducedObservedSystem data)
    (n : Nat)
    {x y : BalancedCoordinates}
    (h : x = y) :
    system.hiddenIterate n x = system.hiddenIterate n y := by
  cases h
  rfl

/-- Equal initial reduced hidden coordinates determine the same observed
trajectory in the reduced observed system. -/
theorem ReducedObservedSystem.observedIterate_congr
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (system : ReducedObservedSystem data)
    (n : Nat)
    {x y : BalancedCoordinates}
    (h : x = y) :
    system.observedIterate n x = system.observedIterate n y := by
  cases h
  rfl

/-- The hidden evolution in the reduced observed system satisfies its own
current-free recurrence law. -/
theorem ReducedObservedSystem.hiddenIterate_step
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (system : ReducedObservedSystem data) :
    ∀ n : Nat,
      ∀ x : BalancedCoordinates,
        system.hiddenIterate (n + 1) x =
          system.hiddenStep (system.hiddenIterate n x)
  | 0, x => rfl
  | n + 1, x => by
      simpa [ReducedObservedSystem.hiddenIterate, iterateEndomorphism] using
        system.hiddenIterate_step n (system.hiddenStep x)

/-- The observed evolution in the reduced observed system is always obtained by
reading the current hidden reduced state. -/
theorem ReducedObservedSystem.observedIterate_readout
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (system : ReducedObservedSystem data)
    (x : BalancedCoordinates) :
    ∀ n : Nat,
      system.observedIterate n x =
        system.observedReadout (system.hiddenIterate n x) := by
  intro n
  rfl

/-- Pure initial-value package for a reduced observed system: only the current-
free reduced dynamics and one initial reduced hidden coordinate remain. -/
structure ReducedObservedInitialState
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (system : ReducedObservedSystem data) where
  initial : BalancedCoordinates

/-- Hidden orbit of a reduced observed system from one initial reduced hidden
coordinate. -/
def ReducedObservedInitialState.hiddenTrajectory
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    {system : ReducedObservedSystem data}
    (state : ReducedObservedInitialState system) :
    Nat → BalancedCoordinates :=
  fun n => system.hiddenIterate n state.initial

/-- Selected observed orbit of a reduced observed system from one initial
reduced hidden coordinate. -/
def ReducedObservedInitialState.observedTrajectory
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    {system : ReducedObservedSystem data}
    (state : ReducedObservedInitialState system) :
    Nat → State :=
  fun n => system.observedIterate n state.initial

/-- The hidden orbit starts at the chosen initial reduced hidden coordinate. -/
theorem ReducedObservedInitialState.hiddenTrajectory_zero
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    {system : ReducedObservedSystem data}
    (state : ReducedObservedInitialState system) :
    state.hiddenTrajectory 0 = state.initial := by
  rfl

/-- The hidden orbit satisfies the system's current-free reduced recurrence. -/
theorem ReducedObservedInitialState.hiddenTrajectory_step
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    {system : ReducedObservedSystem data}
    (state : ReducedObservedInitialState system) :
    ∀ n : Nat,
      state.hiddenTrajectory (n + 1) =
        system.hiddenStep (state.hiddenTrajectory n) := by
  intro n
  exact system.hiddenIterate_step n state.initial

/-- The observed orbit is always the readout of the current hidden reduced
state. -/
theorem ReducedObservedInitialState.observedTrajectory_readout
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    {system : ReducedObservedSystem data}
    (state : ReducedObservedInitialState system) :
    ∀ n : Nat,
      state.observedTrajectory n =
        system.observedReadout (state.hiddenTrajectory n) := by
  intro n
  exact system.observedIterate_readout state.initial n

/-- Every reduced observed system determines the corresponding pure reduced
observed dynamics package. -/
def ReducedObservedSystem.toDynamics
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (system : ReducedObservedSystem data) :
    ReducedObservedDynamics where
  hiddenStep := system.hiddenStep
  observedReadout := system.observedReadout

/-- Every current-free initial state of a reduced observed system determines
the corresponding pure reduced-dynamics initial state. -/
def ReducedObservedInitialState.toDynamicsState
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    {system : ReducedObservedSystem data}
    (state : ReducedObservedInitialState system) :
    ReducedObservedDynamicsState where
  dynamics := system.toDynamics
  initial := state.initial

/-- Passing to the pure reduced-dynamics state does not change the hidden
orbit. -/
theorem ReducedObservedInitialState.hiddenTrajectory_toDynamicsState
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    {system : ReducedObservedSystem data}
    (state : ReducedObservedInitialState system) :
    ∀ n : Nat,
      state.hiddenTrajectory n =
        state.toDynamicsState.hiddenTrajectory n := by
  intro n
  simp [ReducedObservedInitialState.hiddenTrajectory,
    ReducedObservedInitialState.toDynamicsState,
    ReducedObservedDynamicsState.hiddenTrajectory,
    ReducedObservedDynamics.hiddenTrajectoryFrom,
    ReducedObservedSystem.hiddenIterate,
    ReducedObservedSystem.toDynamics]

/-- Passing to the pure reduced-dynamics state does not change the observed
orbit. -/
theorem ReducedObservedInitialState.observedTrajectory_toDynamicsState
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    {system : ReducedObservedSystem data}
    (state : ReducedObservedInitialState system) :
    ∀ n : Nat,
      state.observedTrajectory n =
        state.toDynamicsState.observedTrajectory n := by
  intro n
  simp [ReducedObservedInitialState.observedTrajectory,
    ReducedObservedInitialState.toDynamicsState,
    ReducedObservedDynamicsState.observedTrajectory,
    ReducedObservedDynamics.observedTrajectoryFrom,
    ReducedObservedDynamics.hiddenTrajectoryFrom,
    ReducedObservedSystem.observedIterate,
    ReducedObservedSystem.hiddenIterate,
    ReducedObservedSystem.toDynamics]

/-- Canonical reduced observed system carried by the detached selected-cut
bridge. -/
def AnchoredCurrentObject.reducedObservedSystem
    {Index Time Carrier Law : Type}
    (data : AnchoredCurrentObject Index Time Carrier Law) :
    ReducedObservedSystem data where
  hiddenStep := data.coordinateStep
  observedReadout := BalancedCoordinates.observedReadout data

/-- Current-free hidden trajectory determined by one initial reduced hidden
coordinate on the detached selected-cut bridge. -/
def AnchoredCurrentObject.hiddenTrajectoryFrom
    {Index Time Carrier Law : Type}
    (data : AnchoredCurrentObject Index Time Carrier Law)
    (x : BalancedCoordinates) :
    Nat → BalancedCoordinates :=
  fun n => data.reducedObservedSystem.hiddenIterate n x

/-- Current-free observed trajectory determined by one initial reduced hidden
coordinate on the detached selected-cut bridge. -/
def AnchoredCurrentObject.observedTrajectoryFrom
    {Index Time Carrier Law : Type}
    (data : AnchoredCurrentObject Index Time Carrier Law)
    (x : BalancedCoordinates) :
    Nat → State :=
  fun n => data.reducedObservedSystem.observedIterate n x

/-- The current-free hidden trajectory on the reduced hidden carrier is
generated stepwise by the canonical reduced hidden update map. -/
theorem AnchoredCurrentObject.hiddenTrajectoryFrom_step
    {Index Time Carrier Law : Type}
    (data : AnchoredCurrentObject Index Time Carrier Law) :
    ∀ n : Nat,
      ∀ x : BalancedCoordinates,
        data.hiddenTrajectoryFrom x (n + 1) =
          data.coordinateStep (data.hiddenTrajectoryFrom x n)
  | 0, x => rfl
  | n + 1, x => by
      simpa [AnchoredCurrentObject.hiddenTrajectoryFrom,
        ReducedObservedSystem.hiddenIterate, iterateEndomorphism] using
        data.hiddenTrajectoryFrom_step n (data.coordinateStep x)

/-- The current-free selected observed trajectory is read from the current-free
hidden trajectory by the canonical selected projection. -/
theorem AnchoredCurrentObject.observedTrajectoryFrom_readout
    {Index Time Carrier Law : Type}
    (data : AnchoredCurrentObject Index Time Carrier Law)
    (x : BalancedCoordinates) :
    ∀ n : Nat,
      data.observedTrajectoryFrom x n =
        selectedProjection data.bridge ((data.hiddenTrajectoryFrom x n).toState)
  := by
    intro n
    rfl

/-- Iterated reduced hidden-current transport on the smaller reduced hidden
assembly. -/
def ReducedCurrentAssembly.coordinateIterate
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (_assembly : ReducedCurrentAssembly data) :
    Nat → BalancedCoordinates → BalancedCoordinates :=
  iterateEndomorphism data.coordinateStep

/-- Repeated exactification of the hidden pair current agrees exactly with
repeated reduced transport on the smaller reduced hidden assembly. -/
theorem ReducedCurrentAssembly.coordinateTrajectory
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (assembly : ReducedCurrentAssembly data) :
    ∀ n : Nat,
      ∀ current : PairExchangeCurrent data.currentCarrier data.Leg,
        assembly.currentCoordinates (data.exactifyIterate n current) =
          assembly.coordinateIterate n (assembly.currentCoordinates current)
  | 0, current => rfl
  | n + 1, current => by
      change
        assembly.currentCoordinates (data.exactifyIterate n (data.exactifier.exactify current)) =
          assembly.coordinateIterate n
            (data.coordinateStep (assembly.currentCoordinates current))
      calc
        assembly.currentCoordinates (data.exactifyIterate n (data.exactifier.exactify current)) =
            assembly.coordinateIterate n
              (assembly.currentCoordinates (data.exactifier.exactify current)) :=
          assembly.coordinateTrajectory n (data.exactifier.exactify current)
        _ =
            assembly.coordinateIterate n
              (data.coordinateStep (assembly.currentCoordinates current)) := by
          simpa [AnchoredCurrentObject.coordinateStep] using
            congrArg (assembly.coordinateIterate n) (assembly.coordinateTransport current)

/-- The selected observed state read from the smaller reduced hidden assembly. -/
def ReducedCurrentAssembly.observedState
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (assembly : ReducedCurrentAssembly data) :
    PairExchangeCurrent data.currentCarrier data.Leg → State :=
  fun current => selectedProjection data.bridge ((assembly.currentCoordinates current).toState)

/-- The hidden detached current trajectory already factors through the smaller
reduced hidden assembly. -/
theorem ReducedCurrentAssembly.systemHiddenTrajectory
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (assembly : ReducedCurrentAssembly data) :
    ∀ n : Nat,
      ∀ current : PairExchangeCurrent data.currentCarrier data.Leg,
        assembly.currentCoordinates (data.exactifyIterate n current) =
          (data.reducedObservedSystem.hiddenIterate n)
            (assembly.currentCoordinates current) := by
  intro n current
  simpa [AnchoredCurrentObject.reducedObservedSystem,
    ReducedObservedSystem.hiddenIterate]
    using assembly.coordinateTrajectory n current

/-- The selected observed detached current trajectory already factors through
the smaller reduced hidden assembly. -/
theorem ReducedCurrentAssembly.systemObservedTrajectory
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (assembly : ReducedCurrentAssembly data) :
    ∀ n : Nat,
      ∀ current : PairExchangeCurrent data.currentCarrier data.Leg,
        assembly.observedState (data.exactifyIterate n current) =
          (data.reducedObservedSystem.observedIterate n)
            (assembly.currentCoordinates current) := by
  intro n current
  calc
    assembly.observedState (data.exactifyIterate n current) =
        selectedProjection data.bridge
          ((assembly.currentCoordinates (data.exactifyIterate n current)).toState) := by
      rfl
    _ = selectedProjection data.bridge
          ((assembly.coordinateIterate n (assembly.currentCoordinates current)).toState) := by
      rw [assembly.coordinateTrajectory n current]
    _ = (data.reducedObservedSystem.observedIterate n)
          (assembly.currentCoordinates current) := by
      rfl

/-- After passing to reduced hidden coordinates, the hidden detached current
trajectory is exactly the current-free hidden orbit determined by the initial
reduced coordinate. -/
theorem ReducedCurrentAssembly.hiddenTrajectory_from_initialCoordinate
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (assembly : ReducedCurrentAssembly data) :
    ∀ n : Nat,
      ∀ current : PairExchangeCurrent data.currentCarrier data.Leg,
        assembly.currentCoordinates (data.exactifyIterate n current) =
          data.hiddenTrajectoryFrom (assembly.currentCoordinates current) n := by
  intro n current
  exact assembly.systemHiddenTrajectory n current

/-- After passing to reduced hidden coordinates, the selected observed detached
current trajectory is exactly the current-free observed orbit determined by the
initial reduced coordinate. -/
theorem ReducedCurrentAssembly.observedTrajectory_from_initialCoordinate
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (assembly : ReducedCurrentAssembly data) :
    ∀ n : Nat,
      ∀ current : PairExchangeCurrent data.currentCarrier data.Leg,
        assembly.observedState (data.exactifyIterate n current) =
          data.observedTrajectoryFrom (assembly.currentCoordinates current) n := by
  intro n current
  exact assembly.systemObservedTrajectory n current

/-- Equal initial reduced hidden coordinates already force the same hidden
detached current trajectory on the smaller reduced hidden assembly. -/
theorem ReducedCurrentAssembly.sameCoordinates_sameHiddenTrajectory
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (assembly : ReducedCurrentAssembly data) :
    ∀ n : Nat,
      ∀ current current' : PairExchangeCurrent data.currentCarrier data.Leg,
        assembly.currentCoordinates current =
            assembly.currentCoordinates current' →
          assembly.currentCoordinates (data.exactifyIterate n current) =
            assembly.currentCoordinates (data.exactifyIterate n current') := by
  intro n current current' hcoords
  calc
    assembly.currentCoordinates (data.exactifyIterate n current) =
        (data.reducedObservedSystem.hiddenIterate n)
          (assembly.currentCoordinates current) :=
      assembly.systemHiddenTrajectory n current
    _ =
        (data.reducedObservedSystem.hiddenIterate n)
          (assembly.currentCoordinates current') :=
      data.reducedObservedSystem.hiddenIterate_congr n hcoords
    _ =
        assembly.currentCoordinates (data.exactifyIterate n current') := by
      symm
      exact assembly.systemHiddenTrajectory n current'

/-- Equal initial reduced hidden coordinates already force the same selected
observed detached current trajectory on the smaller reduced hidden assembly. -/
theorem ReducedCurrentAssembly.sameCoordinates_sameObservedTrajectory
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (assembly : ReducedCurrentAssembly data) :
    ∀ n : Nat,
      ∀ current current' : PairExchangeCurrent data.currentCarrier data.Leg,
        assembly.currentCoordinates current =
            assembly.currentCoordinates current' →
          assembly.observedState (data.exactifyIterate n current) =
            assembly.observedState (data.exactifyIterate n current') := by
  intro n current current' hcoords
  calc
    assembly.observedState (data.exactifyIterate n current) =
        (data.reducedObservedSystem.observedIterate n)
          (assembly.currentCoordinates current) :=
      assembly.systemObservedTrajectory n current
    _ =
        (data.reducedObservedSystem.observedIterate n)
          (assembly.currentCoordinates current') :=
      data.reducedObservedSystem.observedIterate_congr n hcoords
    _ =
        assembly.observedState (data.exactifyIterate n current') := by
      symm
      exact assembly.systemObservedTrajectory n current'

/-- Two reduced hidden-state assemblies on the same anchored current object
induce the same hidden trajectory whenever they agree on the initial reduced
hidden coordinates. -/
theorem ReducedCurrentAssembly.sameCoordinates_acrossAssemblies_sameHiddenTrajectory
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (assembly assembly' : ReducedCurrentAssembly data) :
    ∀ n : Nat,
      ∀ current current' : PairExchangeCurrent data.currentCarrier data.Leg,
        assembly.currentCoordinates current =
            assembly'.currentCoordinates current' →
          assembly.currentCoordinates (data.exactifyIterate n current) =
            assembly'.currentCoordinates (data.exactifyIterate n current') := by
  intro n current current' hcoords
  calc
    assembly.currentCoordinates (data.exactifyIterate n current) =
        (data.reducedObservedSystem.hiddenIterate n)
          (assembly.currentCoordinates current) :=
      assembly.systemHiddenTrajectory n current
    _ =
        (data.reducedObservedSystem.hiddenIterate n)
          (assembly'.currentCoordinates current') :=
      data.reducedObservedSystem.hiddenIterate_congr n hcoords
    _ =
        assembly'.currentCoordinates (data.exactifyIterate n current') := by
      symm
      exact assembly'.systemHiddenTrajectory n current'

/-- Two reduced hidden-state assemblies on the same anchored current object
induce the same selected observed trajectory whenever they agree on the
initial reduced hidden coordinates. -/
theorem ReducedCurrentAssembly.sameCoordinates_acrossAssemblies_sameObservedTrajectory
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (assembly assembly' : ReducedCurrentAssembly data) :
    ∀ n : Nat,
      ∀ current current' : PairExchangeCurrent data.currentCarrier data.Leg,
        assembly.currentCoordinates current =
            assembly'.currentCoordinates current' →
          assembly.observedState (data.exactifyIterate n current) =
            assembly'.observedState (data.exactifyIterate n current') := by
  intro n current current' hcoords
  calc
    assembly.observedState (data.exactifyIterate n current) =
        (data.reducedObservedSystem.observedIterate n)
          (assembly.currentCoordinates current) :=
      assembly.systemObservedTrajectory n current
    _ =
        (data.reducedObservedSystem.observedIterate n)
          (assembly'.currentCoordinates current') :=
      data.reducedObservedSystem.observedIterate_congr n hcoords
    _ =
        assembly'.observedState (data.exactifyIterate n current') := by
      symm
      exact assembly'.systemObservedTrajectory n current'

/-- Iterated reduced hidden-current transport on the three-coordinate balanced
carrier. -/
def CurrentStateAssembly.coordinateIterate
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (_assembly : CurrentStateAssembly data) :
    Nat → BalancedCoordinates → BalancedCoordinates :=
  iterateEndomorphism data.coordinateStep

/-- Repeated exactification of the hidden pair current agrees exactly with
repeated reduced transport on the three-coordinate balanced carrier. -/
theorem CurrentStateAssembly.coordinateTrajectory
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (assembly : CurrentStateAssembly data) :
    ∀ n : Nat,
      ∀ current : PairExchangeCurrent data.currentCarrier data.Leg,
        assembly.realizeCoordinates (data.exactifyIterate n current) =
          assembly.coordinateIterate n (assembly.realizeCoordinates current)
  | 0, current => rfl
  | n + 1, current => by
      change
        assembly.realizeCoordinates (data.exactifyIterate n (data.exactifier.exactify current)) =
          assembly.coordinateIterate n
            (data.coordinateStep (assembly.realizeCoordinates current))
      calc
        assembly.realizeCoordinates (data.exactifyIterate n (data.exactifier.exactify current)) =
            assembly.coordinateIterate n
              (assembly.realizeCoordinates (data.exactifier.exactify current)) :=
          assembly.coordinateTrajectory n (data.exactifier.exactify current)
        _ =
            assembly.coordinateIterate n
              (data.coordinateStep (assembly.realizeCoordinates current)) := by
          simpa [AnchoredCurrentObject.coordinateStep] using
            congrArg (assembly.coordinateIterate n) (assembly.coordinateTransport current)

/-- Packaged iterated reduced hidden-current transport on the selected cut. -/
def AssembledUnifiedAnchoredCurrentObject.currentCoordinateIterate
    {Index Time Carrier Law : Type}
    (data : AssembledUnifiedAnchoredCurrentObject Index Time Carrier Law) :
    Nat → BalancedCoordinates → BalancedCoordinates :=
  data.stateField.currentAssembly.coordinateIterate

/-- Canonical reduced observed system in packaged selected-cut form. -/
def AssembledUnifiedAnchoredCurrentObject.reducedObservedSystem
    {Index Time Carrier Law : Type}
    (data : AssembledUnifiedAnchoredCurrentObject Index Time Carrier Law) :
    ReducedObservedSystem data.object :=
  data.object.reducedObservedSystem

/-- Canonical reduced observed system carried by the smaller reduced anchored
current object. -/
def ReducedAnchoredCurrentObject.reducedObservedSystem
    {Index Time Carrier Law : Type}
    (data : ReducedAnchoredCurrentObject Index Time Carrier Law) :
    ReducedObservedSystem data.object :=
  data.object.reducedObservedSystem

/-- Iterated reduced hidden-current transport on the smaller reduced anchored
current object. -/
def ReducedAnchoredCurrentObject.currentCoordinateIterate
    {Index Time Carrier Law : Type}
    (data : ReducedAnchoredCurrentObject Index Time Carrier Law) :
    Nat → BalancedCoordinates → BalancedCoordinates :=
  data.reducedAssembly.coordinateIterate

/-- Selected observed state read from the smaller reduced anchored current
object. -/
def ReducedAnchoredCurrentObject.currentObservedState
    {Index Time Carrier Law : Type}
    (data : ReducedAnchoredCurrentObject Index Time Carrier Law) :
    PairExchangeCurrent data.object.currentCarrier data.object.Leg → State :=
  data.reducedAssembly.observedState

/-- Current-free hidden trajectory determined by one initial reduced hidden
coordinate on the smaller reduced anchored current object. -/
def ReducedAnchoredCurrentObject.hiddenTrajectoryFrom
    {Index Time Carrier Law : Type}
    (data : ReducedAnchoredCurrentObject Index Time Carrier Law)
    (x : BalancedCoordinates) :
    Nat → BalancedCoordinates :=
  data.object.hiddenTrajectoryFrom x

/-- Current-free observed trajectory determined by one initial reduced hidden
coordinate on the smaller reduced anchored current object. -/
def ReducedAnchoredCurrentObject.observedTrajectoryFrom
    {Index Time Carrier Law : Type}
    (data : ReducedAnchoredCurrentObject Index Time Carrier Law)
    (x : BalancedCoordinates) :
    Nat → State :=
  data.object.observedTrajectoryFrom x

/-- On the smaller reduced anchored current object, the current-free hidden
trajectory satisfies the same canonical reduced recurrence law. -/
theorem ReducedAnchoredCurrentObject.hiddenTrajectoryFrom_step
    {Index Time Carrier Law : Type}
    (data : ReducedAnchoredCurrentObject Index Time Carrier Law) :
    ∀ n : Nat,
      ∀ x : BalancedCoordinates,
        data.hiddenTrajectoryFrom x (n + 1) =
          data.object.coordinateStep (data.hiddenTrajectoryFrom x n) :=
  data.object.hiddenTrajectoryFrom_step

/-- On the smaller reduced anchored current object, the current-free selected
observed trajectory is read from the hidden reduced trajectory by the canonical
selected projection. -/
theorem ReducedAnchoredCurrentObject.observedTrajectoryFrom_readout
    {Index Time Carrier Law : Type}
    (data : ReducedAnchoredCurrentObject Index Time Carrier Law)
    (x : BalancedCoordinates) :
    ∀ n : Nat,
      data.observedTrajectoryFrom x n =
        selectedProjection data.object.bridge ((data.hiddenTrajectoryFrom x n).toState) :=
  data.object.observedTrajectoryFrom_readout x

/-- Pure reduced initial-value package for the detached law: one reduced
anchored current object together with one initial reduced hidden coordinate. -/
structure ReducedInitialState (Index Time Carrier Law : Type) where
  system : ReducedAnchoredCurrentObject Index Time Carrier Law
  initial : BalancedCoordinates

/-- Hidden orbit of the detached law from one reduced initial coordinate. -/
def ReducedInitialState.hiddenTrajectory
    {Index Time Carrier Law : Type}
    (data : ReducedInitialState Index Time Carrier Law) :
    Nat → BalancedCoordinates :=
  data.system.hiddenTrajectoryFrom data.initial

/-- Selected observed orbit of the detached law from one reduced initial
coordinate. -/
def ReducedInitialState.observedTrajectory
    {Index Time Carrier Law : Type}
    (data : ReducedInitialState Index Time Carrier Law) :
    Nat → State :=
  data.system.observedTrajectoryFrom data.initial

/-- The hidden orbit starts at the chosen reduced initial coordinate. -/
theorem ReducedInitialState.hiddenTrajectory_zero
    {Index Time Carrier Law : Type}
    (data : ReducedInitialState Index Time Carrier Law) :
    data.hiddenTrajectory 0 = data.initial := by
  rfl

/-- The hidden orbit of the detached law satisfies the canonical reduced
recurrence. -/
theorem ReducedInitialState.hiddenTrajectory_step
    {Index Time Carrier Law : Type}
    (data : ReducedInitialState Index Time Carrier Law) :
    ∀ n : Nat,
      data.hiddenTrajectory (n + 1) =
        data.system.object.coordinateStep (data.hiddenTrajectory n) := by
  intro n
  exact data.system.hiddenTrajectoryFrom_step n data.initial

/-- The selected observed orbit is read from the hidden orbit by the canonical
selected projection. -/
theorem ReducedInitialState.observedTrajectory_readout
    {Index Time Carrier Law : Type}
    (data : ReducedInitialState Index Time Carrier Law) :
    ∀ n : Nat,
      data.observedTrajectory n =
        selectedProjection data.system.object.bridge ((data.hiddenTrajectory n).toState) := by
  intro n
  exact data.system.observedTrajectoryFrom_readout data.initial n

/-- The reduced initial-value package factors through the smaller current-free
initial state of the canonical reduced observed system. -/
def ReducedInitialState.toObservedInitialState
    {Index Time Carrier Law : Type}
    (data : ReducedInitialState Index Time Carrier Law) :
    ReducedObservedInitialState data.system.reducedObservedSystem where
  initial := data.initial

/-- The reduced initial-value package already determines the corresponding pure
reduced-dynamics initial state. -/
def ReducedInitialState.toDynamicsState
    {Index Time Carrier Law : Type}
    (data : ReducedInitialState Index Time Carrier Law) :
    ReducedObservedDynamicsState :=
  data.toObservedInitialState.toDynamicsState

/-- Every detached current on the reduced anchored system determines one
reduced initial state by taking its initial reduced hidden coordinate. -/
def ReducedAnchoredCurrentObject.initialStateOf
    {Index Time Carrier Law : Type}
    (data : ReducedAnchoredCurrentObject Index Time Carrier Law)
    (current : PairExchangeCurrent data.object.currentCarrier data.object.Leg) :
    ReducedInitialState Index Time Carrier Law where
  system := data
  initial := data.reducedAssembly.currentCoordinates current

/-- Every detached current on the reduced anchored system already determines
the smaller current-free initial state of the canonical reduced observed
system. -/
def ReducedAnchoredCurrentObject.observedInitialStateOf
    {Index Time Carrier Law : Type}
    (data : ReducedAnchoredCurrentObject Index Time Carrier Law)
    (current : PairExchangeCurrent data.object.currentCarrier data.object.Leg) :
    ReducedObservedInitialState data.reducedObservedSystem where
  initial := data.reducedAssembly.currentCoordinates current

/-- Every detached current on the reduced anchored system already determines
the corresponding pure reduced-dynamics initial state. -/
def ReducedAnchoredCurrentObject.dynamicsStateOf
    {Index Time Carrier Law : Type}
    (data : ReducedAnchoredCurrentObject Index Time Carrier Law)
    (current : PairExchangeCurrent data.object.currentCarrier data.object.Leg) :
    ReducedObservedDynamicsState :=
  (data.observedInitialStateOf current).toDynamicsState

/-- Every detached current on the reduced anchored system already determines
the smaller bridge-driven reduced initial state: selected bridge generator,
selected projection, and initial reduced hidden coordinate. -/
def ReducedAnchoredCurrentObject.selectedReducedStateOf
    {Index Time Carrier Law : Type}
    (data : ReducedAnchoredCurrentObject Index Time Carrier Law)
    (current : PairExchangeCurrent data.object.currentCarrier data.object.Leg) :
    SelectedReducedState where
  generator := data.object.bridge.generator.toFun
  projection := selectedProjection data.object.bridge
  initial := data.reducedAssembly.currentCoordinates current

/-- Every detached current on the explicit coordinate object already determines
the smaller bridge-driven reduced initial state. -/
def CoordinateAnchoredCurrentObject.selectedReducedStateOf
    {Index Time Carrier Law : Type}
    (data : CoordinateAnchoredCurrentObject Index Time Carrier Law)
    (current : PairExchangeCurrent data.object.currentCarrier data.object.Leg) :
    SelectedReducedState :=
  data.toReducedAnchoredCurrentObject.selectedReducedStateOf current

/-- The selected-cut reduced hidden current already carries a discrete
trajectory law: `n` exactification steps agree exactly with `n` reduced
transport steps on the three-coordinate hidden carrier. -/
theorem AssembledUnifiedAnchoredCurrentObject.currentCoordinateTrajectory
    {Index Time Carrier Law : Type}
    (data : AssembledUnifiedAnchoredCurrentObject Index Time Carrier Law) :
    ∀ n : Nat,
      ∀ current : PairExchangeCurrent data.object.currentCarrier data.object.Leg,
        data.currentCoordinates (data.object.exactifyIterate n current) =
          data.currentCoordinateIterate n (data.currentCoordinates current) := by
  intro n current
  exact data.stateField.currentAssembly.coordinateTrajectory n current

/-- The smaller reduced anchored current object already carries the exact
reduced hidden discrete trajectory law. -/
theorem ReducedAnchoredCurrentObject.currentCoordinateTrajectory
    {Index Time Carrier Law : Type}
    (data : ReducedAnchoredCurrentObject Index Time Carrier Law) :
    ∀ n : Nat,
      ∀ current : PairExchangeCurrent data.object.currentCarrier data.object.Leg,
        data.reducedAssembly.currentCoordinates (data.object.exactifyIterate n current) =
          data.currentCoordinateIterate n (data.reducedAssembly.currentCoordinates current) := by
  intro n current
  exact data.reducedAssembly.coordinateTrajectory n current

/-- In packaged selected-cut form, the hidden detached current trajectory
already factors through the smaller reduced hidden assembly. -/
theorem AssembledUnifiedAnchoredCurrentObject.reducedAssemblyHiddenTrajectory
    {Index Time Carrier Law : Type}
    (data : AssembledUnifiedAnchoredCurrentObject Index Time Carrier Law) :
    ∀ n : Nat,
      ∀ current : PairExchangeCurrent data.object.currentCarrier data.object.Leg,
        data.toReducedCurrentAssembly.currentCoordinates (data.object.exactifyIterate n current) =
          (data.reducedObservedSystem.hiddenIterate n)
            (data.toReducedCurrentAssembly.currentCoordinates current) := by
  intro n current
  exact data.toReducedCurrentAssembly.systemHiddenTrajectory n current

/-- On the smaller reduced anchored current object, the hidden detached current
trajectory is already a trajectory of the canonical reduced observed system. -/
theorem ReducedAnchoredCurrentObject.systemHiddenTrajectory
    {Index Time Carrier Law : Type}
    (data : ReducedAnchoredCurrentObject Index Time Carrier Law) :
    ∀ n : Nat,
      ∀ current : PairExchangeCurrent data.object.currentCarrier data.object.Leg,
        data.reducedAssembly.currentCoordinates (data.object.exactifyIterate n current) =
          (data.reducedObservedSystem.hiddenIterate n)
            (data.reducedAssembly.currentCoordinates current) := by
  intro n current
  exact data.reducedAssembly.systemHiddenTrajectory n current

/-- In packaged selected-cut form, the selected observed detached current
trajectory already factors through the smaller reduced hidden assembly. -/
theorem AssembledUnifiedAnchoredCurrentObject.reducedAssemblyObservedTrajectory
    {Index Time Carrier Law : Type}
    (data : AssembledUnifiedAnchoredCurrentObject Index Time Carrier Law) :
    ∀ n : Nat,
      ∀ current : PairExchangeCurrent data.object.currentCarrier data.object.Leg,
        data.toReducedCurrentAssembly.observedState (data.object.exactifyIterate n current) =
          (data.reducedObservedSystem.observedIterate n)
            (data.toReducedCurrentAssembly.currentCoordinates current) := by
  intro n current
  exact data.toReducedCurrentAssembly.systemObservedTrajectory n current

/-- On the smaller reduced anchored current object, the selected observed
detached current trajectory is already the observed trajectory of the canonical
reduced observed system. -/
theorem ReducedAnchoredCurrentObject.systemObservedTrajectory
    {Index Time Carrier Law : Type}
    (data : ReducedAnchoredCurrentObject Index Time Carrier Law) :
    ∀ n : Nat,
      ∀ current : PairExchangeCurrent data.object.currentCarrier data.object.Leg,
        data.currentObservedState (data.object.exactifyIterate n current) =
          (data.reducedObservedSystem.observedIterate n)
            (data.reducedAssembly.currentCoordinates current) := by
  intro n current
  exact data.reducedAssembly.systemObservedTrajectory n current

/-- On the smaller reduced anchored current object, every hidden detached
current trajectory is exactly the current-free hidden orbit of its initial
reduced coordinate. -/
theorem ReducedAnchoredCurrentObject.hiddenTrajectory_from_initialCoordinate
    {Index Time Carrier Law : Type}
    (data : ReducedAnchoredCurrentObject Index Time Carrier Law) :
    ∀ n : Nat,
      ∀ current : PairExchangeCurrent data.object.currentCarrier data.object.Leg,
        data.reducedAssembly.currentCoordinates (data.object.exactifyIterate n current) =
          data.hiddenTrajectoryFrom (data.reducedAssembly.currentCoordinates current) n := by
  intro n current
  exact data.systemHiddenTrajectory n current

/-- On the smaller reduced anchored current object, every selected observed
detached current trajectory is exactly the current-free observed orbit of its
initial reduced coordinate. -/
theorem ReducedAnchoredCurrentObject.observedTrajectory_from_initialCoordinate
    {Index Time Carrier Law : Type}
    (data : ReducedAnchoredCurrentObject Index Time Carrier Law) :
    ∀ n : Nat,
      ∀ current : PairExchangeCurrent data.object.currentCarrier data.object.Leg,
        data.currentObservedState (data.object.exactifyIterate n current) =
          data.observedTrajectoryFrom (data.reducedAssembly.currentCoordinates current) n := by
  intro n current
  exact data.systemObservedTrajectory n current

/-- The hidden detached current trajectory is exactly the hidden orbit of the
reduced initial-state problem determined by that current. -/
theorem ReducedAnchoredCurrentObject.hiddenTrajectory_initialStateOf
    {Index Time Carrier Law : Type}
    (data : ReducedAnchoredCurrentObject Index Time Carrier Law) :
    ∀ n : Nat,
      ∀ current : PairExchangeCurrent data.object.currentCarrier data.object.Leg,
        data.reducedAssembly.currentCoordinates (data.object.exactifyIterate n current) =
          (data.initialStateOf current).hiddenTrajectory n := by
  intro n current
  exact data.hiddenTrajectory_from_initialCoordinate n current

/-- The selected observed detached current trajectory is exactly the observed
orbit of the reduced initial-state problem determined by that current. -/
theorem ReducedAnchoredCurrentObject.observedTrajectory_initialStateOf
    {Index Time Carrier Law : Type}
    (data : ReducedAnchoredCurrentObject Index Time Carrier Law) :
    ∀ n : Nat,
      ∀ current : PairExchangeCurrent data.object.currentCarrier data.object.Leg,
        data.currentObservedState (data.object.exactifyIterate n current) =
          (data.initialStateOf current).observedTrajectory n := by
  intro n current
  exact data.observedTrajectory_from_initialCoordinate n current

/-- The hidden detached current trajectory is exactly the hidden orbit of the
smaller current-free initial state of the canonical reduced observed system. -/
theorem ReducedAnchoredCurrentObject.hiddenTrajectory_observedInitialStateOf
    {Index Time Carrier Law : Type}
    (data : ReducedAnchoredCurrentObject Index Time Carrier Law) :
    ∀ n : Nat,
      ∀ current : PairExchangeCurrent data.object.currentCarrier data.object.Leg,
        data.reducedAssembly.currentCoordinates (data.object.exactifyIterate n current) =
          (data.observedInitialStateOf current).hiddenTrajectory n := by
  intro n current
  exact data.systemHiddenTrajectory n current

/-- The selected observed detached current trajectory is exactly the observed
orbit of the smaller current-free initial state of the canonical reduced
observed system. -/
theorem ReducedAnchoredCurrentObject.observedTrajectory_observedInitialStateOf
    {Index Time Carrier Law : Type}
    (data : ReducedAnchoredCurrentObject Index Time Carrier Law) :
    ∀ n : Nat,
      ∀ current : PairExchangeCurrent data.object.currentCarrier data.object.Leg,
        data.currentObservedState (data.object.exactifyIterate n current) =
          (data.observedInitialStateOf current).observedTrajectory n := by
  intro n current
  exact data.systemObservedTrajectory n current

/-- The hidden detached current trajectory is exactly the hidden orbit of the
pure reduced-dynamics initial state determined by that current. -/
theorem ReducedAnchoredCurrentObject.hiddenTrajectory_dynamicsStateOf
    {Index Time Carrier Law : Type}
    (data : ReducedAnchoredCurrentObject Index Time Carrier Law) :
    ∀ n : Nat,
      ∀ current : PairExchangeCurrent data.object.currentCarrier data.object.Leg,
        data.reducedAssembly.currentCoordinates (data.object.exactifyIterate n current) =
          (data.dynamicsStateOf current).hiddenTrajectory n := by
  intro n current
  calc
    data.reducedAssembly.currentCoordinates (data.object.exactifyIterate n current) =
        (data.observedInitialStateOf current).hiddenTrajectory n :=
      data.hiddenTrajectory_observedInitialStateOf n current
    _ = (data.dynamicsStateOf current).hiddenTrajectory n := by
      exact (data.observedInitialStateOf current).hiddenTrajectory_toDynamicsState n

/-- The selected observed detached current trajectory is exactly the observed
orbit of the pure reduced-dynamics initial state determined by that current. -/
theorem ReducedAnchoredCurrentObject.observedTrajectory_dynamicsStateOf
    {Index Time Carrier Law : Type}
    (data : ReducedAnchoredCurrentObject Index Time Carrier Law) :
    ∀ n : Nat,
      ∀ current : PairExchangeCurrent data.object.currentCarrier data.object.Leg,
        data.currentObservedState (data.object.exactifyIterate n current) =
          (data.dynamicsStateOf current).observedTrajectory n := by
  intro n current
  calc
    data.currentObservedState (data.object.exactifyIterate n current) =
        (data.observedInitialStateOf current).observedTrajectory n :=
      data.observedTrajectory_observedInitialStateOf n current
    _ = (data.dynamicsStateOf current).observedTrajectory n := by
      exact (data.observedInitialStateOf current).observedTrajectory_toDynamicsState n

/-- The hidden detached current trajectory is exactly the hidden orbit of the
smaller bridge-driven reduced initial state determined by that current. -/
theorem ReducedAnchoredCurrentObject.hiddenTrajectory_selectedReducedStateOf
    {Index Time Carrier Law : Type}
    (data : ReducedAnchoredCurrentObject Index Time Carrier Law) :
    ∀ n : Nat,
      ∀ current : PairExchangeCurrent data.object.currentCarrier data.object.Leg,
        data.reducedAssembly.currentCoordinates (data.object.exactifyIterate n current) =
          (data.selectedReducedStateOf current).hiddenTrajectory n := by
  intro n current
  calc
    data.reducedAssembly.currentCoordinates (data.object.exactifyIterate n current) =
        (data.dynamicsStateOf current).hiddenTrajectory n :=
      data.hiddenTrajectory_dynamicsStateOf n current
    _ = (data.selectedReducedStateOf current).hiddenTrajectory n := by
      symm
      exact (data.selectedReducedStateOf current).hiddenTrajectory_toDynamicsState n

/-- The selected observed detached current trajectory is exactly the observed
orbit of the smaller bridge-driven reduced initial state determined by that
current. -/
theorem ReducedAnchoredCurrentObject.observedTrajectory_selectedReducedStateOf
    {Index Time Carrier Law : Type}
    (data : ReducedAnchoredCurrentObject Index Time Carrier Law) :
    ∀ n : Nat,
      ∀ current : PairExchangeCurrent data.object.currentCarrier data.object.Leg,
        data.currentObservedState (data.object.exactifyIterate n current) =
          (data.selectedReducedStateOf current).observedTrajectory n := by
  intro n current
  calc
    data.currentObservedState (data.object.exactifyIterate n current) =
        (data.dynamicsStateOf current).observedTrajectory n :=
      data.observedTrajectory_dynamicsStateOf n current
    _ = (data.selectedReducedStateOf current).observedTrajectory n := by
      symm
      exact (data.selectedReducedStateOf current).observedTrajectory_toDynamicsState n

/-- On the explicit coordinate object, the hidden detached current trajectory
is exactly the hidden orbit of the selected-bridge reduced state determined by
that current. -/
theorem CoordinateAnchoredCurrentObject.hiddenTrajectory_selectedReducedStateOf
    {Index Time Carrier Law : Type}
    (data : CoordinateAnchoredCurrentObject Index Time Carrier Law) :
    ∀ n : Nat,
      ∀ current : PairExchangeCurrent data.object.currentCarrier data.object.Leg,
        data.coordinateAssembly.currentCoordinates
            (data.object.exactifyIterate n current) =
          (data.selectedReducedStateOf current).hiddenTrajectory n := by
  intro n current
  exact data.toReducedAnchoredCurrentObject.hiddenTrajectory_selectedReducedStateOf n current

/-- On the explicit coordinate object, the selected observed detached current
trajectory is exactly the observed orbit of the selected-bridge reduced state
determined by that current. -/
theorem CoordinateAnchoredCurrentObject.observedTrajectory_selectedReducedStateOf
    {Index Time Carrier Law : Type}
    (data : CoordinateAnchoredCurrentObject Index Time Carrier Law) :
    ∀ n : Nat,
      ∀ current : PairExchangeCurrent data.object.currentCarrier data.object.Leg,
        (data.toReducedAnchoredCurrentObject.currentObservedState)
            (data.object.exactifyIterate n current) =
          (data.selectedReducedStateOf current).observedTrajectory n := by
  intro n current
  exact data.toReducedAnchoredCurrentObject.observedTrajectory_selectedReducedStateOf n current

/-- The hidden detached current trajectory is already a trajectory of the
canonical reduced observed system. -/
theorem CurrentStateAssembly.systemHiddenTrajectory
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (assembly : CurrentStateAssembly data) :
    ∀ n : Nat,
      ∀ current : PairExchangeCurrent data.currentCarrier data.Leg,
        assembly.realizeCoordinates (data.exactifyIterate n current) =
          (data.reducedObservedSystem.hiddenIterate n)
            (assembly.realizeCoordinates current) := by
  intro n current
  simpa [AnchoredCurrentObject.reducedObservedSystem,
    ReducedObservedSystem.hiddenIterate]
    using assembly.coordinateTrajectory n current

/-- Selected observed state read directly from the explicit hidden current
assembly by projection to the selected cut. -/
def CurrentStateAssembly.observedState
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (assembly : CurrentStateAssembly data) :
    PairExchangeCurrent data.currentCarrier data.Leg → State :=
  fun current => selectedProjection data.bridge (assembly.realize current)

/-- The selected observed state is exactly the selected projection of the
concrete assembled four-leg flux state. -/
theorem CurrentStateAssembly.observedFormula
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (assembly : CurrentStateAssembly data) :
    ∀ current : PairExchangeCurrent data.currentCarrier data.Leg,
      assembly.observedState current =
        selectedProjection data.bridge
          ⟨legFlux assembly.readout assembly.frame current assembly.frame.l0,
            legFlux assembly.readout assembly.frame current assembly.frame.l1,
            legFlux assembly.readout assembly.frame current assembly.frame.l2,
            legFlux assembly.readout assembly.frame current assembly.frame.l3⟩ := by
  intro current
  rfl

/-- On realized detached current states, the selected observed state is already
read directly from the reduced hidden coordinates by reconstruction followed by
selected projection. -/
theorem CurrentStateAssembly.observedFromCoordinates
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (assembly : CurrentStateAssembly data) :
    ∀ current : PairExchangeCurrent data.currentCarrier data.Leg,
      assembly.observedState current =
        selectedProjection data.bridge
          ((assembly.realizeCoordinates current).toState) := by
  intro current
  calc
    assembly.observedState current
        = selectedProjection data.bridge
            ((assembly.realizeBalanced current).toState) := by
            rfl
    _ = selectedProjection data.bridge
          ((BalancedCoordinates.toBalancedState
              (assembly.realizeCoordinates current)).toState) := by
          rw [(assembly.coordinateSurface).1 current]
    _ = selectedProjection data.bridge
          ((assembly.realizeCoordinates current).toState) := by
          rfl

/-- Iterated selected observed transport on the selected cut. -/
def CurrentStateAssembly.observedIterate
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (_assembly : CurrentStateAssembly data) :
    Nat → State → State :=
  iterateEndomorphism data.bridge.generator.toFun

/-- The selected observed state evolves by the matched selected generator under
one exactification step of the hidden current. -/
theorem CurrentStateAssembly.observedTransport
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (assembly : CurrentStateAssembly data) :
    ∀ current : PairExchangeCurrent data.currentCarrier data.Leg,
      assembly.observedState (data.exactifier.exactify current) =
        data.bridge.generator.toFun (assembly.observedState current) := by
  intro current
  calc
    assembly.observedState (data.exactifier.exactify current)
        = selectedProjection data.bridge
            (assembly.realize (data.exactifier.exactify current)) := by
            rfl
    _ = selectedProjection data.bridge
          (data.bridge.generator.toFun (assembly.realize current)) := by
          exact congrArg (selectedProjection data.bridge) (assembly.exactifier_realized current)
    _ = data.bridge.generator.toFun
          (selectedProjection data.bridge (assembly.realize current)) := by
          exact (selectedHorizonAutonomousScale data.bridge).2 (assembly.realize current)
    _ = data.bridge.generator.toFun (assembly.observedState current) := by
          rfl

/-- Repeated exactification of the hidden pair current agrees exactly with
repeated selected observed transport on the selected cut. -/
theorem CurrentStateAssembly.observedTrajectory
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (assembly : CurrentStateAssembly data) :
    ∀ n : Nat,
      ∀ current : PairExchangeCurrent data.currentCarrier data.Leg,
        assembly.observedState (data.exactifyIterate n current) =
          assembly.observedIterate n (assembly.observedState current)
  | 0, current => rfl
  | n + 1, current => by
      change
        assembly.observedState (data.exactifyIterate n (data.exactifier.exactify current)) =
          assembly.observedIterate n
            (data.bridge.generator.toFun (assembly.observedState current))
      calc
        assembly.observedState (data.exactifyIterate n (data.exactifier.exactify current)) =
            assembly.observedIterate n
              (assembly.observedState (data.exactifier.exactify current)) :=
          assembly.observedTrajectory n (data.exactifier.exactify current)
        _ =
            assembly.observedIterate n
              (data.bridge.generator.toFun (assembly.observedState current)) := by
          exact congrArg (assembly.observedIterate n) (assembly.observedTransport current)

/-- The realized selected observed trajectory is already read exactly from the
reduced hidden trajectory by reconstruction and selected projection. -/
theorem CurrentStateAssembly.observedCoordinateTrajectory
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (assembly : CurrentStateAssembly data) :
    ∀ n : Nat,
      ∀ current : PairExchangeCurrent data.currentCarrier data.Leg,
        assembly.observedState (data.exactifyIterate n current) =
          selectedProjection data.bridge
            ((assembly.coordinateIterate n
                (assembly.realizeCoordinates current)).toState) := by
  intro n current
  calc
    assembly.observedState (data.exactifyIterate n current)
        = selectedProjection data.bridge
            ((assembly.realizeCoordinates (data.exactifyIterate n current)).toState) := by
            exact assembly.observedFromCoordinates (data.exactifyIterate n current)
    _ = selectedProjection data.bridge
          ((assembly.coordinateIterate n
              (assembly.realizeCoordinates current)).toState) := by
          rw [assembly.coordinateTrajectory n current]

/-- Packaged selected observed-state iterate on the selected cut. -/
def AssembledUnifiedAnchoredCurrentObject.currentObservedIterate
    {Index Time Carrier Law : Type}
    (data : AssembledUnifiedAnchoredCurrentObject Index Time Carrier Law) :
    Nat → State → State :=
  data.stateField.currentAssembly.observedIterate

/-- Packaged selected observed state read directly from the explicit hidden
current assembly. -/
def AssembledUnifiedAnchoredCurrentObject.currentObservedState
    {Index Time Carrier Law : Type}
    (data : AssembledUnifiedAnchoredCurrentObject Index Time Carrier Law) :
    PairExchangeCurrent data.object.currentCarrier data.object.Leg → State :=
  data.stateField.currentAssembly.observedState

/-- The packaged selected observed state is already the selected projection of
the concrete assembled four-leg flux state. -/
theorem AssembledUnifiedAnchoredCurrentObject.currentObservedFormula
    {Index Time Carrier Law : Type}
    (data : AssembledUnifiedAnchoredCurrentObject Index Time Carrier Law) :
    ∀ current : PairExchangeCurrent data.object.currentCarrier data.object.Leg,
      data.currentObservedState current =
        selectedProjection data.object.bridge
          ⟨legFlux data.stateField.currentAssembly.readout
              data.stateField.currentAssembly.frame
              current
              data.stateField.currentAssembly.frame.l0,
            legFlux data.stateField.currentAssembly.readout
              data.stateField.currentAssembly.frame
              current
              data.stateField.currentAssembly.frame.l1,
            legFlux data.stateField.currentAssembly.readout
              data.stateField.currentAssembly.frame
              current
              data.stateField.currentAssembly.frame.l2,
            legFlux data.stateField.currentAssembly.readout
              data.stateField.currentAssembly.frame
              current
              data.stateField.currentAssembly.frame.l3⟩ := by
  intro current
  exact data.stateField.currentAssembly.observedFormula current

/-- Packaged selected observed state read directly from the reduced hidden
coordinates on realized detached current states. -/
theorem AssembledUnifiedAnchoredCurrentObject.currentObservedFromCoordinates
    {Index Time Carrier Law : Type}
    (data : AssembledUnifiedAnchoredCurrentObject Index Time Carrier Law) :
    ∀ current : PairExchangeCurrent data.object.currentCarrier data.object.Leg,
      data.currentObservedState current =
        selectedProjection data.object.bridge
          ((data.currentCoordinates current).toState) := by
  intro current
  exact data.stateField.currentAssembly.observedFromCoordinates current

/-- The selected-cut observed state already carries its own exact discrete
trajectory law under repeated hidden exactification. -/
theorem AssembledUnifiedAnchoredCurrentObject.currentObservedTrajectory
    {Index Time Carrier Law : Type}
    (data : AssembledUnifiedAnchoredCurrentObject Index Time Carrier Law) :
    ∀ n : Nat,
      ∀ current : PairExchangeCurrent data.object.currentCarrier data.object.Leg,
        data.currentObservedState (data.object.exactifyIterate n current) =
          data.currentObservedIterate n (data.currentObservedState current) := by
  intro n current
  exact data.stateField.currentAssembly.observedTrajectory n current

/-- Packaged selected observed trajectory read directly from the reduced hidden
trajectory by reconstruction and selected projection. -/
theorem AssembledUnifiedAnchoredCurrentObject.currentObservedCoordinateTrajectory
    {Index Time Carrier Law : Type}
    (data : AssembledUnifiedAnchoredCurrentObject Index Time Carrier Law) :
    ∀ n : Nat,
      ∀ current : PairExchangeCurrent data.object.currentCarrier data.object.Leg,
        data.currentObservedState (data.object.exactifyIterate n current) =
          selectedProjection data.object.bridge
            ((data.currentCoordinateIterate n (data.currentCoordinates current)).toState) := by
  intro n current
  exact data.stateField.currentAssembly.observedCoordinateTrajectory n current

/-- The selected observed detached current trajectory is already the observed
trajectory of the canonical reduced observed system. -/
theorem CurrentStateAssembly.systemObservedTrajectory
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (assembly : CurrentStateAssembly data) :
    ∀ n : Nat,
      ∀ current : PairExchangeCurrent data.currentCarrier data.Leg,
        assembly.observedState (data.exactifyIterate n current) =
          (data.reducedObservedSystem.observedIterate n)
            (assembly.realizeCoordinates current) := by
  intro n current
  simpa [AnchoredCurrentObject.reducedObservedSystem,
    ReducedObservedSystem.observedIterate,
    ReducedObservedSystem.hiddenIterate,
    BalancedCoordinates.observedReadout]
    using assembly.observedCoordinateTrajectory n current

/-- Equal initial reduced hidden coordinates already force the same hidden
detached current trajectory. -/
theorem CurrentStateAssembly.sameCoordinates_sameHiddenTrajectory
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (assembly : CurrentStateAssembly data) :
    ∀ n : Nat,
      ∀ current current' : PairExchangeCurrent data.currentCarrier data.Leg,
        assembly.realizeCoordinates current =
            assembly.realizeCoordinates current' →
          assembly.realizeCoordinates (data.exactifyIterate n current) =
            assembly.realizeCoordinates (data.exactifyIterate n current') := by
  intro n current current' hcoords
  calc
    assembly.realizeCoordinates (data.exactifyIterate n current) =
        (data.reducedObservedSystem.hiddenIterate n)
          (assembly.realizeCoordinates current) :=
      assembly.systemHiddenTrajectory n current
    _ =
        (data.reducedObservedSystem.hiddenIterate n)
          (assembly.realizeCoordinates current') :=
      data.reducedObservedSystem.hiddenIterate_congr n hcoords
    _ =
        assembly.realizeCoordinates (data.exactifyIterate n current') := by
      symm
      exact assembly.systemHiddenTrajectory n current'

/-- Equal initial reduced hidden coordinates already force the same selected
observed detached current trajectory. -/
theorem CurrentStateAssembly.sameCoordinates_sameObservedTrajectory
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (assembly : CurrentStateAssembly data) :
    ∀ n : Nat,
      ∀ current current' : PairExchangeCurrent data.currentCarrier data.Leg,
        assembly.realizeCoordinates current =
            assembly.realizeCoordinates current' →
          assembly.observedState (data.exactifyIterate n current) =
            assembly.observedState (data.exactifyIterate n current') := by
  intro n current current' hcoords
  calc
    assembly.observedState (data.exactifyIterate n current) =
        (data.reducedObservedSystem.observedIterate n)
          (assembly.realizeCoordinates current) :=
      assembly.systemObservedTrajectory n current
    _ =
        (data.reducedObservedSystem.observedIterate n)
          (assembly.realizeCoordinates current') :=
      data.reducedObservedSystem.observedIterate_congr n hcoords
    _ =
        assembly.observedState (data.exactifyIterate n current') := by
      symm
      exact assembly.systemObservedTrajectory n current'

/-- On one explicit detached current assembly, the reduced hidden trajectory
already depends only on the initial six local slot values. Once two initial
currents agree slot-by-slot on the framed pair carrier, their reduced hidden
trajectories agree at every step. -/
theorem CurrentStateAssembly.sameLocalSlots_sameHiddenTrajectory
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (assembly : CurrentStateAssembly data) :
    ∀ n : Nat,
      ∀ current current' : PairExchangeCurrent data.currentCarrier data.Leg,
        (∀ slot : LocalSlot,
          localSlotReadout assembly.readout assembly.frame current slot =
            localSlotReadout assembly.readout assembly.frame current' slot) →
          assembly.realizeCoordinates (data.exactifyIterate n current) =
            assembly.realizeCoordinates (data.exactifyIterate n current') := by
  intro n current current' hslots
  apply assembly.sameCoordinates_sameHiddenTrajectory n current current'
  exact assembledCoordinates_eq_of_localSlotReadout_eq hslots

/-- On one explicit detached current assembly, the selected observed trajectory
already depends only on the initial six local slot values. Once two initial
currents agree slot-by-slot on the framed pair carrier, their selected
observed trajectories agree at every step. -/
theorem CurrentStateAssembly.sameLocalSlots_sameObservedTrajectory
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (assembly : CurrentStateAssembly data) :
    ∀ n : Nat,
      ∀ current current' : PairExchangeCurrent data.currentCarrier data.Leg,
        (∀ slot : LocalSlot,
          localSlotReadout assembly.readout assembly.frame current slot =
            localSlotReadout assembly.readout assembly.frame current' slot) →
          assembly.observedState (data.exactifyIterate n current) =
            assembly.observedState (data.exactifyIterate n current') := by
  intro n current current' hslots
  apply assembly.sameCoordinates_sameObservedTrajectory n current current'
  exact assembledCoordinates_eq_of_localSlotReadout_eq hslots

/-- Two explicit detached current assemblies on the same anchored current
object induce the same hidden trajectory whenever they agree on the initial
reduced hidden coordinates. -/
theorem CurrentStateAssembly.sameCoordinates_acrossAssemblies_sameHiddenTrajectory
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (assembly assembly' : CurrentStateAssembly data) :
    ∀ n : Nat,
      ∀ current current' : PairExchangeCurrent data.currentCarrier data.Leg,
        assembly.realizeCoordinates current =
            assembly'.realizeCoordinates current' →
          assembly.realizeCoordinates (data.exactifyIterate n current) =
            assembly'.realizeCoordinates (data.exactifyIterate n current') := by
  intro n current current' hcoords
  calc
    assembly.realizeCoordinates (data.exactifyIterate n current) =
        (data.reducedObservedSystem.hiddenIterate n)
          (assembly.realizeCoordinates current) :=
      assembly.systemHiddenTrajectory n current
    _ =
        (data.reducedObservedSystem.hiddenIterate n)
          (assembly'.realizeCoordinates current') :=
      data.reducedObservedSystem.hiddenIterate_congr n hcoords
    _ =
        assembly'.realizeCoordinates (data.exactifyIterate n current') := by
      symm
      exact assembly'.systemHiddenTrajectory n current'

/-- Two explicit detached current assemblies on the same anchored current
object induce the same reduced hidden trajectory whenever their initial
framed pair currents agree slot-by-slot. The concrete readout/frame data are
therefore relevant only through the six local slot values they assign. -/
theorem CurrentStateAssembly.sameLocalSlots_acrossAssemblies_sameHiddenTrajectory
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (assembly assembly' : CurrentStateAssembly data) :
    ∀ n : Nat,
      ∀ current current' : PairExchangeCurrent data.currentCarrier data.Leg,
        (∀ slot : LocalSlot,
          localSlotReadout assembly.readout assembly.frame current slot =
            localSlotReadout assembly'.readout assembly'.frame current' slot) →
          assembly.realizeCoordinates (data.exactifyIterate n current) =
            assembly'.realizeCoordinates (data.exactifyIterate n current') := by
  intro n current current' hslots
  apply assembly.sameCoordinates_acrossAssemblies_sameHiddenTrajectory assembly' n current current'
  exact assembledCoordinates_eq_of_localSlotReadout_eq hslots

/-- Two explicit detached current assemblies on the same anchored current
object induce the same selected observed trajectory whenever they agree on the
initial reduced hidden coordinates. -/
theorem CurrentStateAssembly.sameCoordinates_acrossAssemblies_sameObservedTrajectory
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (assembly assembly' : CurrentStateAssembly data) :
    ∀ n : Nat,
      ∀ current current' : PairExchangeCurrent data.currentCarrier data.Leg,
        assembly.realizeCoordinates current =
            assembly'.realizeCoordinates current' →
          assembly.observedState (data.exactifyIterate n current) =
            assembly'.observedState (data.exactifyIterate n current') := by
  intro n current current' hcoords
  calc
    assembly.observedState (data.exactifyIterate n current) =
        (data.reducedObservedSystem.observedIterate n)
          (assembly.realizeCoordinates current) :=
      assembly.systemObservedTrajectory n current
    _ =
        (data.reducedObservedSystem.observedIterate n)
          (assembly'.realizeCoordinates current') :=
      data.reducedObservedSystem.observedIterate_congr n hcoords
    _ =
        assembly'.observedState (data.exactifyIterate n current') := by
      symm
      exact assembly'.systemObservedTrajectory n current'

/-- Two explicit detached current assemblies on the same anchored current
object induce the same selected observed trajectory whenever their initial
framed pair currents agree slot-by-slot. The selected visible future is
therefore already rigid at the six-slot level. -/
theorem CurrentStateAssembly.sameLocalSlots_acrossAssemblies_sameObservedTrajectory
    {Index Time Carrier Law : Type}
    {data : AnchoredCurrentObject Index Time Carrier Law}
    (assembly assembly' : CurrentStateAssembly data) :
    ∀ n : Nat,
      ∀ current current' : PairExchangeCurrent data.currentCarrier data.Leg,
        (∀ slot : LocalSlot,
          localSlotReadout assembly.readout assembly.frame current slot =
            localSlotReadout assembly'.readout assembly'.frame current' slot) →
          assembly.observedState (data.exactifyIterate n current) =
            assembly'.observedState (data.exactifyIterate n current') := by
  intro n current current' hslots
  apply assembly.sameCoordinates_acrossAssemblies_sameObservedTrajectory assembly' n current current'
  exact assembledCoordinates_eq_of_localSlotReadout_eq hslots

/-- Packaged hidden detached current trajectory as a trajectory of the
canonical reduced observed system. -/
theorem AssembledUnifiedAnchoredCurrentObject.systemHiddenTrajectory
    {Index Time Carrier Law : Type}
    (data : AssembledUnifiedAnchoredCurrentObject Index Time Carrier Law) :
    ∀ n : Nat,
      ∀ current : PairExchangeCurrent data.object.currentCarrier data.object.Leg,
        data.currentCoordinates (data.object.exactifyIterate n current) =
          (data.reducedObservedSystem.hiddenIterate n)
            (data.currentCoordinates current) := by
  intro n current
  exact data.stateField.currentAssembly.systemHiddenTrajectory n current

/-- Packaged selected observed detached current trajectory as the observed
trajectory of the canonical reduced observed system. -/
theorem AssembledUnifiedAnchoredCurrentObject.systemObservedTrajectory
    {Index Time Carrier Law : Type}
    (data : AssembledUnifiedAnchoredCurrentObject Index Time Carrier Law) :
    ∀ n : Nat,
      ∀ current : PairExchangeCurrent data.object.currentCarrier data.object.Leg,
        data.currentObservedState (data.object.exactifyIterate n current) =
          (data.reducedObservedSystem.observedIterate n)
            (data.currentCoordinates current) := by
  intro n current
  exact data.stateField.currentAssembly.systemObservedTrajectory n current

/-- On the selected cut, equal initial reduced hidden coordinates already force
the same hidden detached current trajectory. -/
theorem AssembledUnifiedAnchoredCurrentObject.sameCoordinates_sameHiddenTrajectory
    {Index Time Carrier Law : Type}
    (data : AssembledUnifiedAnchoredCurrentObject Index Time Carrier Law) :
    ∀ n : Nat,
      ∀ current current' : PairExchangeCurrent data.object.currentCarrier data.object.Leg,
        data.currentCoordinates current = data.currentCoordinates current' →
          data.currentCoordinates (data.object.exactifyIterate n current) =
            data.currentCoordinates (data.object.exactifyIterate n current') := by
  intro n current current' hcoords
  exact data.stateField.currentAssembly.sameCoordinates_sameHiddenTrajectory
    n current current' hcoords

/-- On the selected cut, equal initial reduced hidden coordinates already force
the same selected observed detached current trajectory. -/
theorem AssembledUnifiedAnchoredCurrentObject.sameCoordinates_sameObservedTrajectory
    {Index Time Carrier Law : Type}
    (data : AssembledUnifiedAnchoredCurrentObject Index Time Carrier Law) :
    ∀ n : Nat,
      ∀ current current' : PairExchangeCurrent data.object.currentCarrier data.object.Leg,
        data.currentCoordinates current = data.currentCoordinates current' →
          data.currentObservedState (data.object.exactifyIterate n current) =
            data.currentObservedState (data.object.exactifyIterate n current') := by
  intro n current current' hcoords
  exact data.stateField.currentAssembly.sameCoordinates_sameObservedTrajectory
    n current current' hcoords

end ClosureCurrent

end CoherenceCalculus
