import CoherenceCalculus.PartIV.ClosureCurrentContinuumStateObjectCore

namespace CoherenceCalculus

/-!
# PartIV.ClosureCurrentContinuumStateFieldCore

One canonical selected state-field law on the detached selected cut.

`ClosureCurrentContinuumStateObjectCore` already isolates one selected state
object on the concrete carrier `State`. `ClosureCurrentContinuumAutonomousScalarCore`
already isolates one exact autonomous flow, density, residual, and zero set on
that same carrier.

This file fuses those two surfaces into the current law-shaped target object:
one selected state-field law. It is still not a spatial differential PDE. It
is the explicit state-valued law that any later PDE/action realization must
present on the detached selected cut.
-/

namespace ClosureCurrent

/-- One selected state-field law on the concrete selected carrier.

The data record one selected projection, one autonomous flow, one generator,
one density, one residual, and one zero set, all on the same carrier `State`.
The equations certify that these are not parallel primitives: the flow is
already generated by one common generator, and the residual is already the
scalarization of the same generator-density pairing. -/
structure SelectedStateFieldLaw where
  project : State → State
  flow : Nat → State → State
  generator : State → State
  density : State → Nat
  residual : State → SignedCount
  solution : State → Prop
  project_zero : project State.zero = State.zero
  stage_constant : ∀ n : Nat, ∀ x : State, flow n x = generator x
  generator_visible : ∀ x : State, project (generator x) = generator x
  density_eq : ∀ x : State, density x = State.pair x (generator x)
  residual_eq : ∀ x : State, residual x = SignedCount.ofNat (density x)
  solution_eq : ∀ x : State, solution x ↔ residual x = SignedCount.zero

/-- The canonical selected state-field law already carried by the detached
selected cut. -/
def LocalEventFourStateLaw.selectedStateFieldLaw
    {Index Time Carrier Law : Type}
    (data : LocalEventFourStateLaw Index Time Carrier Law) :
    SelectedStateFieldLaw where
  project := data.selectedStateObject.project
  flow := data.selectedAutonomousScalarLaw.flow
  generator := data.selectedStateObject.generator
  density := data.selectedStateObject.density
  residual := data.selectedStateObject.residual
  solution := data.selectedStateObject.solution
  project_zero := data.selectedStateObject.project_zero
  stage_constant := data.selectedAutonomousScalarLaw.stage_constant
  generator_visible := data.selectedStateObject.generator_visible
  density_eq := data.selectedStateObject.density_eq
  residual_eq := data.selectedStateObject.residual_eq
  solution_eq := data.selectedStateObject.solution_eq

/-- Manuscript-facing surface of the canonical selected state-field law.

The selected state object and the autonomous scalar law have already fused: one
state-valued law carries the selected projection, the exact autonomous flow,
the common generator, the quadratic density, the scalar residual, and the
common zero set. -/
def SelectedStateFieldLawSurface
    {Index Time Carrier Law : Type}
    (data : LocalEventFourStateLaw Index Time Carrier Law) : Prop :=
  Nonempty SelectedStateFieldLaw ∧
    (∀ x : State,
      data.selectedStateFieldLaw.project x = data.selectedStateObject.project x) ∧
    (∀ n : Nat, ∀ x : State,
      data.selectedStateFieldLaw.flow n x = data.selectedAutonomousScalarLaw.flow n x) ∧
    (∀ x : State,
      data.selectedStateFieldLaw.generator x = data.selectedStateObject.generator x) ∧
    (∀ x : State,
      data.selectedStateFieldLaw.generator x = data.selectedAutonomousScalarLaw.generator x) ∧
    (∀ x : State,
      data.selectedStateFieldLaw.generator x = data.selectedFieldLaw.operator x) ∧
    (∀ x : State,
      data.selectedStateFieldLaw.density x = data.selectedStateObject.density x) ∧
    (∀ x : State,
      data.selectedStateFieldLaw.density x = data.selectedAutonomousScalarLaw.density x) ∧
    (∀ x : State,
      data.selectedStateFieldLaw.residual x = data.selectedStateObject.residual x) ∧
    (∀ x : State,
      data.selectedStateFieldLaw.residual x = data.selectedAutonomousScalarLaw.residual x) ∧
    (∀ x : State,
      data.selectedStateFieldLaw.solution x ↔ data.selectedStateObject.solution x) ∧
    (∀ x : State,
      data.selectedStateFieldLaw.solution x ↔ data.selectedFieldEquation x) ∧
    (∀ x : State,
      data.selectedStateFieldLaw.solution x ↔ data.scalarPDERealization.solution x) ∧
    (∀ x : State,
      data.selectedStateFieldLaw.solution x ↔ data.scalarActionRealization.stationary x) ∧
    (∀ x : State,
      data.selectedStateFieldLaw.solution x ↔ data.selectedEvolutionLaw.solution x) ∧
    (∀ realization : CompositeFlagshipRealization data,
      ∀ n : Nat,
        ∀ x : State,
          realization.flagship.velocity x = data.selectedStateFieldLaw.generator x ∧
            realization.differential.blockDatum.operator x =
              data.selectedStateFieldLaw.generator x ∧
            realization.differential.blockDatum.blockPP n x =
              data.selectedStateFieldLaw.generator x ∧
            realization.differential.blockDatum.blockPQ n x = State.zero ∧
            realization.differential.blockDatum.blockQP n x = State.zero ∧
            realization.differential.blockDatum.blockQQ n x = State.zero ∧
            realization.differential.flowDatum.effectiveOp n x =
              data.selectedStateFieldLaw.generator x ∧
            realization.derivative.derivativeDatum.derivative x =
              data.selectedStateFieldLaw.generator x ∧
            realization.derivative.derivativeDatum.restriction n x =
              data.selectedStateFieldLaw.project
                (data.selectedStateFieldLaw.generator x) ∧
            realization.derivative.derivativeDatum.observed n x =
              data.selectedStateFieldLaw.project
                (data.selectedStateFieldLaw.generator x) ∧
            realization.derivative.derivativeDatum.defect n x = State.zero ∧
            realization.flagship.density x = data.selectedStateFieldLaw.density x ∧
            realization.flagship.residual x = data.selectedStateFieldLaw.residual x ∧
            (realization.flagship.solution x ↔
              data.selectedStateFieldLaw.solution x))

/-- The detached selected cut already carries one canonical selected
state-field law. The selected state object and the autonomous scalar law have
already fused into one state-valued law object, and every current public
realization package agrees pointwise with it. -/
theorem LocalEventFourStateLaw.selectedStateFieldLawSurface
    {Index Time Carrier Law : Type}
    (data : LocalEventFourStateLaw Index Time Carrier Law) :
    SelectedStateFieldLawSurface data := by
  have hstate : SelectedStateObjectSurface data := data.selectedStateObjectSurface
  have haut : SelectedAutonomousScalarLawSurface data := data.selectedAutonomousScalarLawSurface
  have hform : SelectedRealizedFormSurface data := data.selectedRealizedFormSurface
  obtain
    ⟨_hstateObj, hproject, hstateGeneratorField, _hstateDensity, _hstateResidual,
      hstateResidualAut, hstateSolution, hpde, haction, hevolution,
      hstateRealization⟩ := hstate
  obtain
    ⟨_hforced, hflow, hautGeneratorField, hautDensity, _hautDensityReal,
      _hautDensityGoal, hautResidual, _hautResidualDensity, hautSolution,
      _hpdeAut, _hactionAut, _hevolutionAut⟩ :=
    haut
  obtain ⟨_hcomposite, hoperator, _hscalar⟩ := hform
  have hfieldGeneratorAut :
      ∀ x : State,
        data.selectedStateFieldLaw.generator x = data.selectedAutonomousScalarLaw.generator x := by
    intro x
    calc
      data.selectedStateFieldLaw.generator x = data.selectedStateObject.generator x := by
        rfl
      _ = data.selectedFieldLaw.operator x := by
        exact hstateGeneratorField x
      _ = data.selectedAutonomousScalarLaw.generator x := by
        symm
        exact hautGeneratorField x
  refine ⟨⟨data.selectedStateFieldLaw⟩, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_,
    ?_, ?_, ?_, ?_, ?_⟩
  · intro x
    rfl
  · intro n x
    rfl
  · intro x
    rfl
  · intro x
    calc
      data.selectedStateFieldLaw.generator x = data.selectedStateObject.generator x := by
        rfl
      _ = data.selectedFieldLaw.operator x := by
        exact hstateGeneratorField x
      _ = data.selectedAutonomousScalarLaw.generator x := by
        symm
        exact hautGeneratorField x
  · intro x
    calc
      data.selectedStateFieldLaw.generator x = data.selectedStateObject.generator x := by
        rfl
      _ = data.selectedFieldLaw.operator x := by
        exact hstateGeneratorField x
  · intro x
    rfl
  · intro x
    calc
      data.selectedStateFieldLaw.density x = data.selectedStateObject.density x := by
        rfl
      _ = data.selectedAutonomousScalarLaw.density x := by
        symm
        exact hautDensity x
  · intro x
    rfl
  · intro x
    calc
      data.selectedStateFieldLaw.residual x = data.selectedStateObject.residual x := by
        rfl
      _ = data.selectedAutonomousScalarLaw.residual x := by
        exact hstateResidualAut x
  · intro x
    rfl
  · intro x
    exact hautSolution x
  · intro x
    exact hpde x
  · intro x
    exact haction x
  · intro x
    exact hevolution x
  · intro realization n x
    have hop := hoperator realization n x
    have hstatex := hstateRealization realization x
    rcases hop with
      ⟨_hvel, hblockOp, hblockPP, hblockPQ, hblockQP, hblockQQ, hflowOp, hderiv,
        hrestrict, hobserved, hdefect⟩
    rcases hstatex with ⟨hvelState, hdensityState, hresidualState, hsolutionState⟩
    refine
      ⟨?_, ?_, ?_, hblockPQ, hblockQP, hblockQQ, hflowOp, ?_, ?_, ?_, hdefect,
        ?_, ?_, ?_⟩
    · calc
        realization.flagship.velocity x = data.selectedStateObject.generator x := by
          exact hvelState
        _ = data.selectedStateFieldLaw.generator x := by
          rfl
    · calc
        realization.differential.blockDatum.operator x =
            data.selectedAutonomousScalarLaw.generator x := by
              exact hblockOp
        _ = data.selectedStateFieldLaw.generator x := by
              symm
              exact hfieldGeneratorAut x
    · calc
        realization.differential.blockDatum.blockPP n x =
            data.selectedAutonomousScalarLaw.generator x := by
              exact hblockPP
        _ = data.selectedStateFieldLaw.generator x := by
              symm
              exact hfieldGeneratorAut x
    · calc
        realization.derivative.derivativeDatum.derivative x =
            data.selectedAutonomousScalarLaw.generator x := by
              exact hderiv
        _ = data.selectedStateFieldLaw.generator x := by
              symm
              exact hfieldGeneratorAut x
    · calc
        realization.derivative.derivativeDatum.restriction n x =
            data.framed.object.bridge.selectedBridge.observer.selection.selectedProjection
              (data.selectedAutonomousScalarLaw.generator x) := by
                exact hrestrict
        _ = data.framed.object.bridge.selectedBridge.observer.selection.selectedProjection
              (data.selectedStateFieldLaw.generator x) := by
                rw [hfieldGeneratorAut x]
        _ = data.selectedStateFieldLaw.project
              (data.selectedStateFieldLaw.generator x) := by
              rfl
    · calc
        realization.derivative.derivativeDatum.observed n x =
            data.framed.object.bridge.selectedBridge.observer.selection.selectedProjection
              (data.selectedAutonomousScalarLaw.generator x) := by
                exact hobserved
        _ = data.framed.object.bridge.selectedBridge.observer.selection.selectedProjection
              (data.selectedStateFieldLaw.generator x) := by
                rw [hfieldGeneratorAut x]
        _ = data.selectedStateFieldLaw.project
              (data.selectedStateFieldLaw.generator x) := by
              rfl
    · calc
        realization.flagship.density x = data.selectedStateObject.density x := by
          exact hdensityState
        _ = data.selectedStateFieldLaw.density x := by
          rfl
    · calc
        realization.flagship.residual x = data.selectedStateObject.residual x := by
          exact hresidualState
        _ = data.selectedStateFieldLaw.residual x := by
          rfl
    · calc
        realization.flagship.solution x ↔ data.selectedStateObject.solution x := by
          exact hsolutionState
        _ ↔ data.selectedStateFieldLaw.solution x := by
          rfl

end ClosureCurrent

end CoherenceCalculus
